import type {
  AuditoriaCamada,
  AuditLogEntry,
  AudExec,
  AvaliacaoRiscoSla,
  Capa,
  ConsumoPeca,
  DocumentoQualidade,
  FornecedorQualidade,
  GateFornecedor,
  GarantiaCaso,
  IndicadorIndustrial,
  InstrumentoMetrologia,
  IsoReadinessItem,
  MudancaQualidade,
  NCRegistro,
  OsAssistencia,
  OSTransitionLog,
  Parametro,
  RegraRiscoSla,
  ReqMaterial,
  SACAtendimentoAnexo,
  SACAtendimento,
  SACRequisicao,
  ScarFornecedor,
  EstudoMsa,
  TreinamentoParticipante,
  TreinamentoQualidade,
  UxMetricEntry,
  Usuario,
} from "../types/contracts.js";

const now = new Date().toISOString().slice(0, 10);

export const db = {
  usuarios: [
    { id: "USR-001", nome: "Carlos Silva", email: "carlos@rodrigues.com.br", perfil: "ADMIN", ativo: true },
    { id: "USR-002", nome: "Maria Costa", email: "maria@rodrigues.com.br", perfil: "SAC", ativo: true },
    { id: "USR-003", nome: "Ana Souza", email: "ana@rodrigues.com.br", perfil: "QUALIDADE", ativo: true },
    { id: "USR-004", nome: "Cleiton Ramos", email: "cleiton.ramos@hotmail.com", perfil: "ADMIN", ativo: true },
  ] as Usuario[],
  auditLog: [] as AuditLogEntry[],
  parametros: [
    { chave: "SLA_GARANTIA_DIAS", valor: "30", descricao: "Prazo maximo garantia" },
    { chave: "SLA_NC_DIAS", valor: "15", descricao: "Prazo maximo NC" },
  ] as Parametro[],

  atendimentos: [] as SACAtendimento[],
  sacAtendimentoAnexos: [] as SACAtendimentoAnexo[],
  requisicoesSac: [] as SACRequisicao[],

  garantias: [] as GarantiaCaso[],
  ncs: [] as NCRegistro[],
  capas: [] as Capa[],
  auditorias: [] as AudExec[],
  auditoriaTemplates: [
    { id: "TPL-5S", nome: "Auditoria 5S", tipoAuditoria: "5S" },
    { id: "TPL-PROC", nome: "Auditoria de Processo", tipoAuditoria: "PROCESSO" },
    { id: "TPL-ISO", nome: "Auditoria ISO 9001", tipoAuditoria: "ISO_9001" },
  ],
  auditoriaTemplateItems: {
    "TPL-5S": ["Utilizacao", "Organizacao", "Limpeza"],
    "TPL-PROC": ["Conformidade do processo", "Rastreabilidade"],
    "TPL-ISO": ["Contexto da organizacao", "Lideranca", "Operacao"],
  } as Record<string, string[]>,

  documentosQualidade: [
    {
      id: "DOC-001",
      codigo: "IT-QUAL-001",
      titulo: "Instrucao de Inspecao Final de Colchoes",
      tipo: "INSTRUCAO_TRABALHO",
      status: "VIGENTE",
      versaoAtual: "3.2",
      responsavel: "Ana Souza",
      setor: "Qualidade",
      validadeAt: "2026-12-31",
      aprovadoPor: "Diretoria Tecnica",
      createdAt: now,
      updatedAt: now,
    },
  ] as DocumentoQualidade[],
  treinamentosQualidade: [
    {
      id: "TRN-001",
      titulo: "Boas praticas de inspecao",
      tipo: "QUALIDADE",
      cargoAlvo: "Inspetor de Qualidade",
      instrutor: "Juliana Costa",
      cargaHoraria: 8,
      status: "PLANEJADO",
      dataPlanejada: "2026-03-25",
      validadeMeses: 12,
    },
  ] as TreinamentoQualidade[],
  treinamentoParticipantes: [] as TreinamentoParticipante[],
  mudancasQualidade: [
    {
      id: "MOC-001",
      titulo: "Troca de fornecedor de espuma D45",
      descricao: "Avaliar impacto da substituicao de materia-prima no processo de laminacao.",
      tipo: "PROCESSO",
      area: "Engenharia de Produto",
      solicitante: "Ricardo Lima",
      risco: "ALTO",
      status: "EM_ANALISE",
      dataSolicitacao: now,
      aprovador: "Comite de Mudancas",
      planoValidacao: "Lote piloto e ensaio de conforto e durabilidade.",
    },
  ] as MudancaQualidade[],
  fornecedoresQualidade: [
    {
      id: "FOR-001",
      codigo: "F0001",
      nome: "Espumas Norte Ltda",
      categoria: "ESPUMA",
      status: "HOMOLOGADO",
      score: 88,
      ultimaAvaliacaoAt: "2026-02-12",
      responsavel: "Suprimentos",
    },
  ] as FornecedorQualidade[],
  scarsFornecedores: [
    {
      id: "SCAR-001",
      fornecedorId: "FOR-001",
      titulo: "Densidade fora da especificacao",
      descricao: "Lote E45 apresentou variacao acima do limite acordado.",
      status: "ABERTA",
      gravidade: "ALTA",
      responsavel: "Mariana Torres",
      prazo: "2026-03-28",
      dataAbertura: now,
    },
  ] as ScarFornecedor[],
  metrologiaInstrumentos: [
    {
      id: "INS-001",
      codigo: "PAQ-001",
      descricao: "Paquimetro digital linha 01",
      tipo: "PAQUIMETRO",
      fabricante: "Mitutoyo",
      numeroSerie: "M-982311",
      planta: "MAO",
      local: "Laboratorio Metrologia",
      statusCalibracao: "CALIBRADO",
      ultimaCalibracaoAt: "2026-01-12",
      proximaCalibracaoAt: "2027-01-12",
      incerteza: 0.02,
      responsavel: "Andre Matos",
    },
  ] as InstrumentoMetrologia[],
  metrologiaMsa: [
    {
      id: "MSA-001",
      instrumentoId: "INS-001",
      caracteristica: "Altura do bloco de espuma",
      metodo: "R&R cruzado",
      rrPercent: 8.5,
      ndc: 6,
      resultado: "APROVADO",
      estudadoAt: "2026-02-20",
      responsavel: "Andre Matos",
      observacoes: "Atende criterio de variacao <= 10%.",
    },
  ] as EstudoMsa[],
  indicadoresIndustriais: [
    {
      id: "KPI-001",
      data: "2026-03-09",
      planta: "MAO",
      linha: "L1-ESPUMA",
      oee: 78.4,
      fpy: 95.2,
      scrapRate: 2.3,
      reworkRate: 1.1,
      mtbfHoras: 56,
      mttrHoras: 2.4,
      paradasNaoPlanejadas: 2,
      fonte: "MES",
    },
  ] as IndicadorIndustrial[],
  regrasRiscoSla: [
    { id: "RISK-001", origemTipo: "SAC", criticidade: "BAIXA", pontuacaoMin: 1, pontuacaoMax: 20, slaHoras: 72, resposta: "Acompanhamento rotina" },
    { id: "RISK-002", origemTipo: "SAC", criticidade: "ALTA", pontuacaoMin: 21, pontuacaoMax: 60, slaHoras: 24, resposta: "Escalonar para lider" },
    { id: "RISK-003", origemTipo: "NC", criticidade: "CRITICA", pontuacaoMin: 61, pontuacaoMax: 125, slaHoras: 8, resposta: "Acao imediata com bloqueio" },
  ] as RegraRiscoSla[],
  avaliacoesRiscoSla: [
    {
      id: "RSLA-001",
      origemTipo: "NC",
      origemId: "NC-001",
      criticidade: "ALTA",
      impacto: 4,
      recorrencia: 3,
      detectabilidade: 2,
      pontuacao: 24,
      slaHoras: 24,
      statusSla: "NO_PRAZO",
      limiteAt: "2026-03-11T18:00:00.000Z",
      criadoAt: "2026-03-10T09:00:00.000Z",
      justificativa: "Recorrencia no processo de colagem.",
    },
  ] as AvaliacaoRiscoSla[],
  auditoriasCamadas: [
    {
      id: "LPA-001",
      camada: "L1",
      planta: "BEL",
      area: "Montagem",
      processo: "Fechamento de tampo",
      auditor: "Supervisor Turno A",
      frequencia: "DIARIA",
      status: "PLANEJADA",
      proximaExecucaoAt: "2026-03-11",
      score: 92,
    },
  ] as AuditoriaCamada[],
  gatesFornecedores: [
    {
      id: "GATE-001",
      fornecedorId: "FOR-001",
      coreTool: "PPAP",
      status: "APROVADO",
      evidencia: "PPAP nivel 3 aprovado",
      validadoPor: "Qualidade Fornecedores",
      validadoAt: "2026-02-10",
    },
  ] as GateFornecedor[],
  isoReadiness: [
    {
      id: "ISO-001",
      clausula: "6.1",
      titulo: "Acoes para riscos e oportunidades",
      status: "EM_ANDAMENTO",
      responsavel: "Coordenacao Qualidade",
      prazo: "2026-07-31",
      evidencia: "Matriz de riscos revisada",
      ultimaRevisaoAt: "2026-03-09",
      risco: "MEDIO",
    },
  ] as IsoReadinessItem[],

  osAssistencia: [] as OsAssistencia[],
  reqMaterial: [] as ReqMaterial[],
  consumoPeca: [] as ConsumoPeca[],
  osTransitionLog: [] as OSTransitionLog[],
  uxMetrics: [] as UxMetricEntry[],
};

export function nextId(prefix: string, currentLength: number): string {
  return `${prefix}-${String(currentLength + 1).padStart(3, "0")}`;
}

export function appendAudit(
  acao: string,
  entidade: string,
  entidadeId: string,
  detalhes: string,
  usuario = "system",
): void {
  db.auditLog.unshift({
    id: nextId("LOG", db.auditLog.length),
    data: new Date().toISOString().replace("T", " ").slice(0, 16),
    usuario,
    acao,
    entidade,
    entidadeId,
    detalhes,
  });
}

if (db.atendimentos.length === 0) {
  db.atendimentos.push({
    id: "SAC-001",
    codcli: "1042",
    clienteNome: "Magazine Luiza",
    cgcent: "47.960.950/0001-21",
    telefone: "(92) 3232-1010",
    canal: "TELEFONE",
    tipoContato: "RECLAMACAO",
    descricao: "Cliente relata afundamento no colchao.",
    plantaResp: "MAO",
    numPedido: "PED-88421",
    numNfVenda: "NF-112340",
    codprod: "COL-QN-001",
    produtoRelacionado: "COL-QN-001 - Colchao Queen Premium",
    status: "ABERTO",
    abertoAt: now,
    atualizadoAt: now,
    timeline: [],
  });
}
