/**
 * Seed data for Inspeções module — real legacy data.
 * 15 sectors, ~1004 checklist items, ~167 NC types, 16 spring patterns.
 */
import { db } from "./dataStore.js";
import { randomUUID } from "node:crypto";

// ── SETORES REAIS ──
export const SETORES_REAIS = [
  "ESPUMAÇÃO",
  "ÁREA DE CURA",
  "FLOCADEIRA",
  "LAMINAÇÃO",
  "MOLA",
  "BORDADEIRA",
  "CORTE E COSTURA",
  "MARCENARIA",
  "TAPEÇARIA",
  "FECHAMENTO",
  "MÓVEIS",
  "EMBALAGEM",
  "ALMOXARIFADO",
  "ESTOFAMENTO",
  "EMBALAGEM DE BASE",
] as const;

// ── MÁQUINAS REAIS DE MOLA ──
export const MAQUINAS_REAIS = ["01", "02", "03", "04"] as const;

// Helper
let _itemCounter = 0;
function itemId() { return `ITEM-${String(++_itemCounter).padStart(4, "0")}`; }

function makeItem(descricao: string, ordem: number, obrigatorio = true, exigeEvidenciaNc = true, exigeTipoNc = true) {
  return { id: itemId(), descricao, ordem, obrigatorio, exigeEvidenciaNc, exigeTipoNc, ativo: true };
}

// ── ITENS DE CHECKLIST POR SETOR ──

const itensEspumacao = [
  "Verificar temperatura do forno de espumação",
  "Verificar pressão de injeção dos componentes químicos",
  "Verificar dosagem do poliol (conforme ficha técnica)",
  "Verificar dosagem do isocianato (conforme ficha técnica)",
  "Verificar dosagem do catalisador",
  "Verificar dosagem do silicone",
  "Verificar tempo de cream time",
  "Verificar tempo de gel time",
  "Verificar tempo de rise time",
  "Verificar temperatura ambiente da área de espumação",
  "Verificar umidade relativa do ar",
  "Verificar funcionamento do misturador",
  "Verificar rotação do misturador (RPM)",
  "Verificar vazão do soprador de ar",
  "Verificar alinhamento da correia transportadora",
  "Verificar velocidade da correia transportadora",
  "Verificar limpeza do cabeçote de mistura",
  "Verificar limpeza dos bicos injetores",
  "Verificar calibração dos medidores de vazão",
  "Verificar calibração dos termômetros",
  "Verificar estado dos moldes (limpeza e conservação)",
  "Verificar aplicação de desmoldante",
  "Verificar ausência de vazamentos nas conexões",
  "Verificar funcionamento do exaustor",
  "Verificar pressão do ar comprimido",
  "Verificar qualidade visual da espuma (cor uniforme)",
  "Verificar ausência de bolhas na superfície",
  "Verificar ausência de buracos internos",
  "Verificar densidade da espuma (corte de amostra)",
  "Verificar altura do bloco espumado",
  "Verificar largura do bloco espumado",
  "Verificar comprimento do bloco espumado",
  "Verificar maciez/firmeza conforme especificação",
  "Verificar odor (ausência de cheiro forte)",
  "Verificar rastreabilidade do lote (etiqueta)",
  "Verificar registro do lote no sistema",
  "Verificar limpeza geral da área de trabalho",
  "Verificar EPI dos operadores",
  "Verificar sinalização de segurança",
  "Verificar extintor de incêndio (validade e acesso)",
  "Verificar condição dos cabos e mangueiras",
  "Verificar funcionamento da esteira de resfriamento",
  "Verificar corte lateral do bloco (esquadro)",
  "Verificar armazenamento temporário do bloco",
  "Verificar identificação do produto na área",
  "Verificar checklist anterior assinado",
  "Verificar registro de início de turno",
  "Verificar manutenção preventiva em dia",
  "Verificar reação química uniforme no molde",
  "Verificar tempo de desmolde",
  "Verificar peso do bloco espumado",
  "Verificar resistência à tração (quando aplicável)",
  "Verificar resiliência da espuma",
  "Verificar dureza ILD da espuma",
  "Verificar deformação permanente por compressão",
  "Verificar validade dos produtos químicos",
  "Verificar fichas de segurança dos produtos (FISPQ)",
  "Verificar ausência de contaminação no material",
  "Verificar segregação de resíduos químicos",
  "Verificar funcionamento do painel de controle",
  "Verificar registro de manutenção corretiva",
  "Verificar condição do piso (antiderrapante e limpo)",
  "Verificar iluminação da área de trabalho",
  "Verificar ventilação adequada",
  "Verificar descarte correto de sobras",
  "Verificar integridade da embalagem dos químicos",
  "Verificar conformidade do certificado do fornecedor",
  "Verificar balança calibrada para pesagem",
  "Verificar conformidade da cor da espuma com amostra padrão",
  "Verificar homogeneidade da espuma cortada",
];

const itensAreaCura = [
  "Verificar temperatura da área de cura",
  "Verificar umidade da área de cura",
  "Verificar tempo mínimo de cura do bloco",
  "Verificar identificação dos blocos em cura",
  "Verificar rastreabilidade (lote + data/hora)",
  "Verificar espaçamento entre blocos para ventilação",
  "Verificar ausência de deformação durante cura",
  "Verificar posicionamento correto dos blocos",
  "Verificar ausência de contato entre blocos",
  "Verificar registro de tempo de entrada na área",
  "Verificar registro de tempo de saída da área",
  "Verificar odor residual após cura (dentro do padrão)",
  "Verificar maciez após cura completa",
  "Verificar firmeza após cura completa",
  "Verificar dimensões pós-cura (altura)",
  "Verificar dimensões pós-cura (largura)",
  "Verificar dimensões pós-cura (comprimento)",
  "Verificar integridade visual do bloco curado",
  "Verificar liberação para laminação/corte",
  "Verificar limpeza geral da área",
  "Verificar sinalização de blocos não conformes",
  "Verificar segregação de blocos rejeitados",
  "Verificar fluxo FIFO (primeiro a entrar, primeiro a sair)",
  "Verificar condição da estrutura de armazenagem",
  "Verificar ventilação forçada em funcionamento",
  "Verificar EPI dos operadores da área",
  "Verificar ausência de materiais estranhos na área",
  "Verificar placa de identificação do produto",
  "Verificar anotação no formulário de controle",
  "Verificar aprovação do inspetor para liberação",
  "Verificar registro de não conformidades durante a cura",
  "Verificar calibração do termômetro da área",
  "Verificar calibração do higrômetro da área",
  "Verificar estado do piso da área de cura",
  "Verificar cobertura/proteção dos blocos contra poeira",
  "Verificar iluminação da área de cura",
  "Verificar extintor de incêndio na área",
  "Verificar densidade pós-cura (teste de amostra)",
  "Verificar resiliência pós-cura",
  "Verificar cor uniforme do bloco após cura",
  "Verificar ausência de rachaduras superficiais",
  "Verificar registro de temperatura ao longo do dia",
  "Verificar registro de umidade ao longo do dia",
  "Verificar peso do bloco após cura completa",
  "Verificar empilhamento máximo respeitado",
  "Verificar sinalização de saída de emergência",
  "Verificar manutenção preventiva dos ventiladores",
  "Verificar condição dos paletes de apoio",
  "Verificar ausência de infiltração na área",
  "Verificar conformidade do bloco com ficha técnica",
  "Verificar documentação de rastreabilidade completa",
  "Verificar envio para próxima etapa (registro)",
  "Verificar checklist anterior assinado",
  "Verificar preenchimento do relatório de turno",
  "Verificar condição das paredes/divisórias da área",
  "Verificar ausência de odor de mofo",
  "Verificar limpeza ao final do turno",
  "Verificar registro de início e fim de turno",
  "Verificar condição dos EPI antes de iniciar",
  "Verificar rotulagem de blocos por tipo/densidade",
  "Verificar segregação por tipo de espuma",
  "Verificar manutenção corretiva registrada",
  "Verificar conformidade com procedimento operacional padrão",
  "Verificar ata de reunião de qualidade (quando aplicável)",
  "Verificar contagem de blocos em cura",
];

const itensFlocadeira = [
  "Verificar funcionamento da máquina flocadeira",
  "Verificar alinhamento das lâminas de corte",
  "Verificar afiação das lâminas",
  "Verificar velocidade de corte (RPM)",
  "Verificar tamanho dos flocos de espuma",
  "Verificar uniformidade dos flocos",
  "Verificar alimentação contínua da máquina",
  "Verificar ausência de entupimento no duto de saída",
  "Verificar funcionamento do sistema de aspiração",
  "Verificar filtros do sistema de aspiração",
  "Verificar limpeza dos filtros",
  "Verificar nível de ruído (dentro do limite)",
  "Verificar vibração anormal da máquina",
  "Verificar proteções e guardas de segurança",
  "Verificar botão de emergência funcional",
  "Verificar limpeza da área ao redor da máquina",
  "Verificar separação por tipo/densidade de espuma",
  "Verificar ausência de contaminação nos flocos",
  "Verificar pesagem dos flocos para preenchimento",
  "Verificar densidade do material flocado",
  "Verificar armazenamento adequado dos flocos",
  "Verificar etiqueta de identificação do lote flocado",
  "Verificar EPI dos operadores",
  "Verificar registro de produção",
  "Verificar manutenção preventiva em dia",
  "Verificar condição dos rolos alimentadores",
  "Verificar esteira de transporte dos flocos",
  "Verificar calibração da balança de pesagem",
  "Verificar consumo de energia da máquina",
  "Verificar registro de paradas/ocorrências",
  "Verificar temperatura do motor da flocadeira",
  "Verificar correia de transmissão (tensão e desgaste)",
  "Verificar lubrificação dos mancais",
  "Verificar condição dos rolamentos",
  "Verificar sistema elétrico (cabos e conexões)",
  "Verificar painel de comando operacional",
  "Verificar sensor de presença/segurança",
  "Verificar descarte correto de resíduos",
  "Verificar identificação de resíduos perigosos",
  "Verificar condição do duto de exaustão",
  "Verificar fixação da máquina ao piso",
  "Verificar iluminação da estação de trabalho",
  "Verificar conformidade do floco com amostra padrão",
  "Verificar registro de manutenção corretiva",
  "Verificar checklist anterior assinado",
  "Verificar relatório de produção diário",
  "Verificar aprovação do inspetor para liberação",
  "Verificar condição do piso (antiderrapante)",
  "Verificar sinalização de segurança da área",
  "Verificar treinamento do operador em dia",
  "Verificar segregação de material não conforme",
  "Verificar vazão de ar do sistema de aspiração",
  "Verificar pressão do ar comprimido",
  "Verificar condição das mangueiras pneumáticas",
  "Verificar registro de troca de lâminas",
  "Verificar conformidade com procedimento operacional",
  "Verificar anotação de setup da máquina",
  "Verificar contagem de produção por turno",
  "Verificar envio para próxima etapa (registro)",
  "Verificar condição da estrutura de armazenagem de flocos",
  "Verificar mistura homogênea de densidades quando requerida",
  "Verificar umidade dos flocos armazenados",
  "Verificar rastreabilidade do lote original da espuma",
  "Verificar documentação de rastreabilidade completa",
  "Verificar ventilação adequada na área",
];

const itensLaminacao = [
  "Verificar calibração da lâmina de corte horizontal",
  "Verificar espessura do corte conforme especificação",
  "Verificar uniformidade da espessura",
  "Verificar esquadro do corte",
  "Verificar alinhamento do bloco na máquina",
  "Verificar velocidade da lâmina",
  "Verificar altura do rolo guia",
  "Verificar funcionamento do sistema de medição",
  "Verificar trena/paquímetro calibrado",
  "Verificar tolerância dimensional (±2mm)",
  "Verificar superfície da lâmina cortada (sem rasgos)",
  "Verificar superfície da lâmina cortada (sem ondulações)",
  "Verificar ausência de marcas na superfície",
  "Verificar identificação das lâminas cortadas",
  "Verificar separação por espessura",
  "Verificar separação por densidade",
  "Verificar limpeza da área de corte",
  "Verificar aspiração de resíduos de espuma",
  "Verificar descarte correto de refiles",
  "Verificar aproveitamento de sobras (reaproveitamento)",
  "Verificar EPI dos operadores",
  "Verificar registro de produção no sistema",
  "Verificar manutenção preventiva da serra",
  "Verificar proteção de segurança da máquina",
  "Verificar botão de emergência funcional",
  "Verificar iluminação adequada na área de corte",
  "Verificar acúmulo de material na máquina",
  "Verificar rastreabilidade do lote original",
  "Verificar conformidade com a ficha de produção",
  "Verificar estado da mesa de apoio/suporte",
  "Verificar empilhamento adequado das lâminas",
  "Verificar envio para próxima etapa (registro)",
  "Verificar liberação de qualidade do lote",
  "Verificar medição de 3 pontos da lâmina",
  "Verificar densidade da espuma laminada",
  "Verificar aparência visual da superfície cortada",
  "Verificar perpendicularidade do corte",
  "Verificar condição da correia de avanço",
  "Verificar nivelamento da mesa da máquina",
  "Verificar calibração do display de medição",
  "Verificar anotação de medidas no formulário",
  "Verificar aprovação do inspetor para despacho",
  "Verificar condição de armazenamento temporário",
  "Verificar ventilação adequada na área",
  "Verificar limpeza ao final do turno",
  "Verificar condição do sistema pneumático da máquina",
  "Verificar tensão da correia do motor",
  "Verificar condição dos rolamentos da serra",
  "Verificar nível de vibração da máquina",
  "Verificar funcionamento do contador de peças",
  "Verificar temperatura do motor da máquina",
  "Verificar fixação da máquina ao piso",
  "Verificar condição das conexões elétricas",
  "Verificar sensor de segurança funcional",
  "Verificar lubrificação dos guias lineares",
  "Verificar condição do painel de controle",
  "Verificar registro de troca de lâmina",
  "Verificar treinamento do operador em dia",
  "Verificar conformidade do lote com pedido de produção",
  "Verificar segregação de peças com defeito",
  "Verificar contagem de produção por turno",
  "Verificar documentação de rastreabilidade completa",
];

const itensMola = [
  "Verificar tipo de arame conforme especificação",
  "Verificar bitola do arame (calibre)",
  "Verificar funcionamento da máquina ensacadeira",
  "Verificar setup da máquina conforme modelo",
  "Verificar altura da mola conforme padrão",
  "Verificar diâmetro da mola conforme padrão",
  "Verificar número de espiras conforme padrão",
  "Verificar passo da mola conforme padrão",
  "Verificar força de compressão (mínimo/máximo)",
  "Verificar deformação da mola sob carga",
  "Verificar tratamento térmico realizado",
  "Verificar temperatura do forno de têmpera",
  "Verificar tempo de têmpera",
  "Verificar dureza da mola após têmpera",
  "Verificar ensacamento correto (sem inversão)",
  "Verificar selagem do tecido TNT",
  "Verificar gramatura do TNT conforme especificação",
  "Verificar ausência de molas furadas no TNT",
  "Verificar alinhamento das molas no painel",
  "Verificar quantidade de molas por fileira",
  "Verificar quantidade de fileiras por painel",
  "Verificar colagem entre fileiras (se aplicável)",
  "Verificar moldura/quadro lateral do painel",
  "Verificar esquadro do painel montado",
  "Verificar dimensões do painel (comprimento)",
  "Verificar dimensões do painel (largura)",
  "Verificar dimensões do painel (altura)",
  "Verificar ruído das molas ao comprimir",
  "Verificar ausência de molas soltas",
  "Verificar ausência de molas deformadas",
  "Verificar resistência do TNT à tração",
  "Verificar teste de fadiga (quando aplicável)",
  "Verificar etiqueta de identificação do lote",
  "Verificar registro de produção",
  "Verificar velocidade da máquina (molas/minuto)",
  "Verificar limpeza da máquina ao iniciar turno",
  "Verificar nível de óleo lubrificante",
  "Verificar condição das matrizes/ferramentais",
  "Verificar proteções de segurança da máquina",
  "Verificar botão de emergência funcional",
  "Verificar EPI dos operadores",
  "Verificar iluminação da área de molas",
  "Verificar aspiração de resíduos metálicos",
  "Verificar descarte de molas defeituosas",
  "Verificar separação de sucata metálica",
  "Verificar manutenção preventiva em dia",
  "Verificar calibração de instrumentos de medição",
  "Verificar arame conforme certificado do fornecedor",
  "Verificar estoque de matéria-prima (arame + TNT)",
  "Verificar status operacional da máquina",
  "Verificar registro de parada/manutenção",
  "Verificar coleta de amostras para ensaio",
  "Verificar aprovação do lote pelo inspetor",
  "Verificar armazenamento dos painéis montados",
  "Verificar empilhamento máximo permitido",
  "Verificar envio para montagem (registro)",
  "Verificar documentação de rastreabilidade completa",
  "Verificar conformidade do arame com norma técnica",
  "Verificar resistência da solda de emenda do arame",
  "Verificar condição das molas de retorno da máquina",
  "Verificar alinhamento do alimentador de arame",
  "Verificar tensão do arame na alimentação",
  "Verificar limpeza geral ao final do turno",
  "Verificar preenchimento do relatório de produção diário",
  "Verificar marcação de não conformidades no painel",
  "Verificar anotação de setup da máquina",
  "Verificar conformidade das dimensões com a amostra padrão",
  "Verificar homogeneidade das molas no painel",
  "Verificar nível de vibração da máquina",
  "Verificar condição do sistema pneumático",
];

const itensBordadeira = [
  "Verificar agulha da bordadeira (tipo e estado)",
  "Verificar linha de bordar (cor e resistência)",
  "Verificar tensão da linha superior",
  "Verificar tensão da linha inferior (bobina)",
  "Verificar ponto por centímetro conforme padrão",
  "Verificar padrão do bordado conforme modelo",
  "Verificar alinhamento do bordado na peça",
  "Verificar centragem do bordado",
  "Verificar ausência de falhas no bordado",
  "Verificar ausência de linhas soltas",
  "Verificar ausência de pontos pulados",
  "Verificar ausência de enrugamento do tecido",
  "Verificar cor do bordado conforme amostra",
  "Verificar acabamento das pontas (corte de linhas)",
  "Verificar dimensões do bordado (altura x largura)",
  "Verificar posição do logotipo/marca",
  "Verificar qualidade do tecido base",
  "Verificar identificação da peça bordada",
  "Verificar separação por modelo/coleção",
  "Verificar limpeza da máquina bordadeira",
  "Verificar lubrificação da máquina",
  "Verificar velocidade de bordado (ppm)",
  "Verificar troca de agulha conforme programação",
  "Verificar manutenção preventiva em dia",
  "Verificar EPI do operador",
  "Verificar iluminação na estação de trabalho",
  "Verificar condição da mesa/bastidor de bordar",
  "Verificar calibração do sensor de ruptura de linha",
  "Verificar registro de produção",
  "Verificar inspeção visual 100% das peças",
  "Verificar quantidade produzida vs planejada",
  "Verificar armazenamento das peças bordadas",
  "Verificar retrabalho de peças com defeito",
  "Verificar descarte de peças irrecuperáveis",
  "Verificar rastreabilidade do lote de tecido",
  "Verificar conformidade com ficha de produção",
  "Verificar funcionamento do cortador de linha automático",
  "Verificar desgaste da chapa de agulha",
  "Verificar tensão da correia do motor",
  "Verificar programa de bordado correto carregado",
  "Verificar condição do motor principal",
  "Verificar condição dos rolamentos da máquina",
  "Verificar painel de controle operacional",
  "Verificar sistema de parada de emergência testado",
  "Verificar fixação do bastidor na máquina",
  "Verificar alinhamento dos cabeçotes de bordado",
  "Verificar bobina inferior (quantidade e qualidade)",
  "Verificar tipo de agulha conforme tecido",
  "Verificar posicionamento do tecido antes de iniciar",
  "Verificar teste de bordado em amostra",
  "Verificar limpeza dos resíduos de linha",
  "Verificar condição das molas tensoras",
  "Verificar registro de troca de agulha",
  "Verificar conformidade do bordado com gabarito",
  "Verificar separação de peças aprovadas e rejeitadas",
  "Verificar identificação do operador na produção",
  "Verificar controle de qualidade por amostragem",
  "Verificar preenchimento do formulário de turno",
  "Verificar temperatura ambiente da área de bordado",
  "Verificar ergonomia do posto de trabalho",
  "Verificar ventilação da área de bordado",
  "Verificar documentação de rastreabilidade completa",
  "Verificar conformidade com amostra padrão aprovada",
  "Verificar envio para próxima etapa (registro)",
  "Verificar contagem de produção diária",
];

const itensCorteECostura = [
  "Verificar afiação da lâmina de corte",
  "Verificar tipo de tecido conforme ficha de produção",
  "Verificar metragem do tecido na mesa de corte",
  "Verificar alinhamento do tecido sobre a mesa",
  "Verificar risco/molde correto para o modelo",
  "Verificar aproveitamento do tecido (% de perda)",
  "Verificar esquadro do corte",
  "Verificar dimensões das peças cortadas",
  "Verificar quantidade de camadas no enfesto",
  "Verificar separação por lote/cor/modelo",
  "Verificar identificação das peças cortadas",
  "Verificar ausência de defeitos no tecido (antes do corte)",
  "Verificar costura reta (sem desvio)",
  "Verificar costura overlock (acabamento)",
  "Verificar ponto por centímetro na costura",
  "Verificar tensão da linha de costura",
  "Verificar linha conforme cor e material",
  "Verificar agulha conforme tipo de tecido",
  "Verificar resistência da costura (teste de tração manual)",
  "Verificar acabamento de viés/debruns",
  "Verificar zíper (funcional e alinhado)",
  "Verificar elástico (tensão e posicionamento)",
  "Verificar etiqueta de composição costurada",
  "Verificar etiqueta da marca costurada",
  "Verificar ausência de pontos pulados",
  "Verificar ausência de desfiamentos",
  "Verificar medidas da peça costurada conforme gabarito",
  "Verificar emenda de tecido (se permitida)",
  "Verificar alinhamento de estampa/padrão",
  "Verificar limpeza das peças (sem manchas de óleo)",
  "Verificar limpeza da máquina de costura",
  "Verificar lubrificação da máquina de costura",
  "Verificar troca de agulha conforme programação",
  "Verificar manutenção preventiva da máquina",
  "Verificar EPI da costureira",
  "Verificar ergonomia da estação de trabalho",
  "Verificar iluminação adequada",
  "Verificar registro de produção",
  "Verificar peças com defeito separadas",
  "Verificar retrabalho efetuado corretamente",
  "Verificar separação de peças para próxima etapa",
  "Verificar conformidade com amostra padrão",
  "Verificar preenchimento do formulário de produção",
  "Verificar descarte correto de retalhos",
  "Verificar conformidade do fio de costura com norma",
  "Verificar funcionamento do cortador de linha",
  "Verificar posicionamento correto de alças/puxadores",
  "Verificar bordas rebatidas (sem franjas)",
  "Verificar simetria da peça finalizada",
  "Verificar acabamento dos cantos e curvas",
  "Verificar armazenamento intermediário correto",
  "Verificar rastreabilidade do lote de tecido",
  "Verificar aprovação visual do inspetor",
  "Verificar conformidade das cores com pedido",
  "Verificar separação de peças por tamanho",
  "Verificar identificação do operador na peça",
  "Verificar controle de defeitos por operador",
  "Verificar velocidade da máquina conforme material",
  "Verificar condição dos calcadores e chapas",
  "Verificar calibração do ajuste de ponto",
  "Verificar temperatura ambiente da área de costura",
  "Verificar condição do pedal da máquina",
  "Verificar condição da bobina e carretilha",
  "Verificar nível de óleo da máquina de costura",
  "Verificar registro de manutenção corretiva",
  "Verificar documentação de rastreabilidade completa",
  "Verificar envio para próxima etapa (registro)",
];

const itensMarcenaria = [
  "Verificar tipo de madeira/MDF conforme especificação",
  "Verificar umidade da madeira (higrômetro)",
  "Verificar espessura do painel de MDF/MDP",
  "Verificar esquadro das peças cortadas",
  "Verificar dimensões das peças conforme projeto",
  "Verificar acabamento da superfície cortada",
  "Verificar ausência de lascas/trincas nas bordas",
  "Verificar furação conforme gabarito",
  "Verificar profundidade dos furos",
  "Verificar posição dos furos para ferragens",
  "Verificar encaixe das ferragens (dobradiças, corrediças)",
  "Verificar aplicação de cola (tipo e quantidade)",
  "Verificar tempo de prensagem (se aplicável)",
  "Verificar acabamento de borda (fita de borda)",
  "Verificar aderência da fita de borda",
  "Verificar ausência de excesso de cola nas bordas",
  "Verificar nivelamento da superfície",
  "Verificar montagem de estruturas (esquadro e prumo)",
  "Verificar resistência da estrutura montada",
  "Verificar lixamento (granulação adequada)",
  "Verificar pintura/verniz/laca conforme amostra",
  "Verificar uniformidade da pintura",
  "Verificar ausência de escorrimentos de tinta",
  "Verificar secagem adequada da pintura",
  "Verificar cor conforme amostra padrão",
  "Verificar identificação do produto/lote",
  "Verificar ferragens de montagem (parafusos, cavilhas)",
  "Verificar funcionamento de portas e gavetas",
  "Verificar alinhamento de portas e gavetas",
  "Verificar EPI dos operadores",
  "Verificar limpeza da área de trabalho",
  "Verificar aspiração de pó de madeira",
  "Verificar iluminação adequada",
  "Verificar manutenção preventiva das máquinas",
  "Verificar calibração da serra circular/esquadrejadeira",
  "Verificar afiação das serras",
  "Verificar funcionamento do exaustor",
  "Verificar condição dos gabaritos de furação",
  "Verificar registro de produção",
  "Verificar segregação de peças não conformes",
  "Verificar descarte correto de resíduos de madeira",
  "Verificar embalagem de proteção da peça",
  "Verificar inspeção final antes do envio",
  "Verificar rastreabilidade com ficha de produção",
  "Verificar aprovação do inspetor de qualidade",
  "Verificar condição das brocas e fresas",
  "Verificar alinhamento da furadeira múltipla",
  "Verificar pressão da prensa pneumática",
  "Verificar condição dos grampos e sargentos",
  "Verificar secagem da cola antes de prosseguir",
  "Verificar conformidade do laminado decorativo",
  "Verificar espessura da fita de borda utilizada",
  "Verificar aderência da cola na fita de borda (teste)",
  "Verificar condição do compressor de ar",
  "Verificar registro de troca de ferramental",
  "Verificar conformidade com desenho técnico",
  "Verificar controle de qualidade por amostragem",
  "Verificar acabamento das dobradiças instaladas",
  "Verificar funcionamento das corrediças",
  "Verificar torque dos parafusos de fixação",
  "Verificar condição das pistolas de cola",
  "Verificar ventilação na área de pintura",
  "Verificar uso de máscara na área de pintura",
  "Verificar temperatura e umidade para aplicação de verniz",
  "Verificar documentação de rastreabilidade completa",
  "Verificar envio para próxima etapa (registro)",
];

const itensTapecaria = [
  "Verificar tipo de tecido conforme ficha de produção",
  "Verificar cor do tecido conforme amostra",
  "Verificar estampa/padronagem conforme pedido",
  "Verificar ausência de defeitos no tecido (manchas, furos)",
  "Verificar metragem do tecido",
  "Verificar gramatura do tecido",
  "Verificar resistência à tração do tecido",
  "Verificar resistência ao pilling (boleamento)",
  "Verificar solidez da cor à luz",
  "Verificar solidez da cor à lavagem",
  "Verificar corte do tecido conforme molde",
  "Verificar dimensões da peça cortada",
  "Verificar alinhamento do tecido sobre a espuma/estrutura",
  "Verificar tensão do tecido ao revestir",
  "Verificar grampeamento/fixação do tecido",
  "Verificar espaçamento dos grampos",
  "Verificar ausência de rugas no revestimento",
  "Verificar acabamento dos cantos",
  "Verificar acabamento das dobras",
  "Verificar alinhamento de costuras visíveis",
  "Verificar simetria do revestimento",
  "Verificar aspecto visual final do estofamento",
  "Verificar conforto ao sentar (teste funcional)",
  "Verificar fixação de botões/capitonê (se aplicável)",
  "Verificar etiqueta de composição aplicada",
  "Verificar etiqueta da marca aplicada",
  "Verificar identificação do produto",
  "Verificar limpeza da área de tapeçaria",
  "Verificar EPI do tapeceiro",
  "Verificar condição da grampeadeira pneumática",
  "Verificar pressão do ar comprimido",
  "Verificar manutenção preventiva dos equipamentos",
  "Verificar registro de produção",
  "Verificar rastreabilidade do lote de tecido",
  "Verificar aprovação visual do inspetor",
  "Verificar retrabalho de peças com defeito",
  "Verificar descarte/segregação de peças irrecuperáveis",
  "Verificar armazenamento do produto revestido",
  "Verificar iluminação adequada na estação",
  "Verificar conformidade com amostra padrão",
  "Verificar condição da grampeadeira elétrica",
  "Verificar condição do compressor de ar",
  "Verificar mangueiras pneumáticas (vazamentos)",
  "Verificar tensão do tecido nos cantos",
  "Verificar colagem do tecido (quando aplicável)",
  "Verificar tipo de cola utilizado",
  "Verificar temperatura da cola (pistola térmica)",
  "Verificar acabamento do fundo do estofado",
  "Verificar fixação do tecido no fundo",
  "Verificar condição dos grampos (tamanho e tipo)",
  "Verificar posicionamento de botões decorativos",
  "Verificar alinhamento de costuras laterais",
  "Verificar identificação do operador na peça",
  "Verificar controle de defeitos por operador",
  "Verificar treinamento do tapeceiro em dia",
  "Verificar ergonomia do posto de trabalho",
  "Verificar separação de peças por modelo/pedido",
  "Verificar conformidade com ficha de produção",
  "Verificar teste de resistência do grampeamento",
  "Verificar acabamento das bordas inferiores",
  "Verificar contagem de produção diária",
  "Verificar documentação de rastreabilidade completa",
  "Verificar envio para próxima etapa (registro)",
  "Verificar condição dos moldes/gabaritos de corte",
];

const itensFechamento = [
  "Verificar montagem do conjunto (mola + espuma + tecido)",
  "Verificar alinhamento dos componentes",
  "Verificar fixação da espuma sobre o painel de molas",
  "Verificar colagem da espuma (tipo e quantidade de cola)",
  "Verificar camadas de espuma conforme especificação",
  "Verificar manta de fibra/feltro aplicada",
  "Verificar gramatura da manta conforme padrão",
  "Verificar costura do pillow top (se aplicável)",
  "Verificar preenchimento do pillow top",
  "Verificar fechamento lateral do colchão",
  "Verificar costura de fechamento (resistência e acabamento)",
  "Verificar viés lateral (cor e aderência)",
  "Verificar alças laterais fixadas corretamente",
  "Verificar resistência das alças à tração",
  "Verificar válvula de ar instalada e funcional",
  "Verificar etiqueta de composição costurada/colada",
  "Verificar etiqueta de garantia",
  "Verificar etiqueta de identificação do modelo/tamanho",
  "Verificar dimensões finais do colchão (comprimento)",
  "Verificar dimensões finais do colchão (largura)",
  "Verificar dimensões finais do colchão (altura)",
  "Verificar esquadro do colchão fechado",
  "Verificar ausência de deformações visíveis",
  "Verificar firmeza/maciez conforme classificação do modelo",
  "Verificar ausência de pontos duros ou irregularidades",
  "Verificar aparência geral (sem manchas, sujeiras ou fios soltos)",
  "Verificar peso do colchão conforme faixa esperada",
  "Verificar teste funcional (sentar/deitar)",
  "Verificar odor do produto final",
  "Verificar EPI dos operadores",
  "Verificar limpeza da área de fechamento",
  "Verificar condição das máquinas de fechamento",
  "Verificar manutenção preventiva em dia",
  "Verificar registro de produção",
  "Verificar rastreabilidade dos componentes",
  "Verificar aprovação final do inspetor",
  "Verificar liberação para embalagem",
  "Verificar documentação de rastreabilidade completa",
  "Verificar conformidade com ficha técnica do modelo",
  "Verificar segregação de unidades não conformes",
  "Verificar solução de NC pendentes do lote",
  "Verificar ata/registro de reunião de qualidade (quando aplicável)",
  "Verificar contagem de produção diária",
  "Verificar envio correto para setor de embalagem",
  "Verificar acabamento das extremidades do colchão",
  "Verificar condição da máquina de fechar lateral",
  "Verificar agulha da máquina de fechamento",
  "Verificar tipo de linha utilizado no fechamento",
  "Verificar tensão da linha de fechamento",
  "Verificar acabamento do viés nos cantos",
  "Verificar posição da válvula de ar no colchão",
  "Verificar resistência da costura lateral (teste)",
  "Verificar condição dos pés de apoio/berço de montagem",
  "Verificar limpeza do produto antes de fechar",
  "Verificar conformidade do pillow top com amostra",
  "Verificar alinhamento da manta sobre a espuma",
  "Verificar fixação da manta com grampos/cola",
  "Verificar camada de feltro conforme especificação",
  "Verificar espessura total do colchão montado",
  "Verificar posicionamento correto das alças",
  "Verificar simetria do produto finalizado",
  "Verificar treinamento do operador em dia",
  "Verificar documentação de rastreabilidade completa",
  "Verificar identificação do operador na produção",
  "Verificar controle de defeitos por operador",
  "Verificar ergonomia do posto de trabalho",
];

const itensMoveis = [
  "Verificar tipo de material conforme especificação",
  "Verificar acabamento da superfície (pintura/laca/verniz)",
  "Verificar cor conforme amostra padrão",
  "Verificar dimensões conforme projeto",
  "Verificar esquadro da estrutura",
  "Verificar nivelamento da base/pés",
  "Verificar fixação das ferragens",
  "Verificar funcionamento de mecanismos (recliner, articulação)",
  "Verificar revestimento do estofado",
  "Verificar costura do estofado (resistência e acabamento)",
  "Verificar conforto funcional (teste de uso)",
  "Verificar resistência estrutural (teste de carga)",
  "Verificar ausência de pontas afiadas ou rebarbas",
  "Verificar identificação do produto (etiqueta)",
  "Verificar manual de montagem/uso incluído",
  "Verificar kit de ferragens para montagem (se aplicável)",
  "Verificar embalagem de proteção adequada",
  "Verificar aspecto visual geral",
  "Verificar EPI dos operadores",
  "Verificar limpeza da área de trabalho",
  "Verificar manutenção preventiva das máquinas",
  "Verificar registro de produção",
  "Verificar rastreabilidade do lote",
  "Verificar aprovação do inspetor de qualidade",
  "Verificar segregação de peças não conformes",
  "Verificar retrabalho executado corretamente",
  "Verificar condição dos gabaritos de montagem",
  "Verificar torque dos parafusos",
  "Verificar soldas (se aplicável)",
  "Verificar alinhamento de portas/gavetas/tampas",
  "Verificar deslizamento de gavetas (corrediças)",
  "Verificar acabamento de bordas (sem lascas)",
  "Verificar colagem (tempo e pressão adequados)",
  "Verificar empilhamento/armazenamento correto",
  "Verificar envio para embalagem (registro)",
  "Verificar condição da pistola de grampos",
  "Verificar pressão do ar comprimido (grampeadeira)",
  "Verificar fixação de tecido na estrutura",
  "Verificar condição do sistema de pintura/verniz",
  "Verificar tempo de secagem entre demãos",
  "Verificar gramatura do tecido de revestimento",
  "Verificar posicionamento de puxadores/alças",
  "Verificar altura do assento conforme padrão",
  "Verificar profundidade do assento conforme padrão",
  "Verificar ângulo do encosto conforme especificação",
  "Verificar acabamento da base/estrutura",
  "Verificar teste de estabilidade (anti-tombamento)",
  "Verificar condição das espumas de encosto",
  "Verificar conformidade do kit de parafusos",
  "Verificar manual de montagem conferido",
  "Verificar condição do sistema de recline (se aplicável)",
  "Verificar trava de segurança do recline",
  "Verificar identificação do operador na produção",
  "Verificar controle de defeitos por operador",
  "Verificar ergonomia do posto de trabalho",
  "Verificar treinamento do operador em dia",
  "Verificar conformidade com amostra padrão",
  "Verificar documentação de rastreabilidade completa",
  "Verificar contagem de produção diária",
  "Verificar ata de reunião de qualidade (quando aplicável)",
  "Verificar acabamento das soldas (quando aplicável)",
  "Verificar pintura eletrostática conforme padrão",
  "Verificar embalagem de proteção individual",
  "Verificar segregação de peças por modelo/cor",
  "Verificar condição dos gabaritos de furação",
  "Verificar teste funcional de articulação",
];

const itensEmbalagem = [
  "Verificar produto conforme antes de embalar",
  "Verificar limpeza do produto antes de embalar",
  "Verificar tipo de embalagem conforme modelo",
  "Verificar plástico stretch aplicado corretamente",
  "Verificar proteção dos cantos (cantoneiras)",
  "Verificar proteção da superfície (filme/plástico)",
  "Verificar etiqueta de identificação do produto",
  "Verificar etiqueta de código de barras",
  "Verificar etiqueta de destino/cliente (se aplicável)",
  "Verificar dimensões da embalagem",
  "Verificar peso da embalagem",
  "Verificar selagem da embalagem",
  "Verificar ausência de danos no produto durante embalagem",
  "Verificar compactação/enrolamento (colchão em caixa, se aplicável)",
  "Verificar vácuo aplicado corretamente (se aplicável)",
  "Verificar caixa de papelão (resistência e dimensão)",
  "Verificar impressão na caixa (modelo/marca)",
  "Verificar manual incluído na embalagem",
  "Verificar garantia incluída na embalagem",
  "Verificar acessórios incluídos (se aplicável)",
  "Verificar paletização correta",
  "Verificar empilhamento máximo respeitado",
  "Verificar amarração do palete (cintas/stretch)",
  "Verificar rastreabilidade (etiqueta do lote)",
  "Verificar registro de produção/embalagem",
  "Verificar limpeza da área de embalagem",
  "Verificar condição da seladora/embaladora",
  "Verificar manutenção preventiva dos equipamentos",
  "Verificar EPI dos operadores",
  "Verificar liberação para expedição",
  "Verificar conformidade com pedido de venda",
  "Verificar quantidade embalada vs pedido",
  "Verificar segregação de unidades com problema de embalagem",
  "Verificar armazenamento temporário adequado",
  "Verificar iluminação da área",
  "Verificar condição da esteira de embalagem",
  "Verificar temperatura da seladora",
  "Verificar condição do rolo de plástico stretch",
  "Verificar condição da máquina de vácuo",
  "Verificar pressão de vácuo (manômetro)",
  "Verificar condição dos rolos de filme plástico",
  "Verificar registro de troca de material de embalagem",
  "Verificar impressora de etiquetas funcionando",
  "Verificar calibração da balança de pesagem",
  "Verificar condição dos paletes utilizados",
  "Verificar amarração do palete conforme padrão",
  "Verificar conferência final antes do embarque",
  "Verificar endereçamento do produto para expedição",
  "Verificar nota fiscal conferida com produto",
  "Verificar registro fotográfico da embalagem (quando requerido)",
  "Verificar treinamento do operador em dia",
  "Verificar ergonomia do posto de trabalho",
  "Verificar identificação do operador na produção",
  "Verificar controle de defeitos por operador",
  "Verificar condição dos equipamentos de movimentação",
  "Verificar conformidade com padrão de embalagem aprovado",
  "Verificar documentação de rastreabilidade completa",
  "Verificar contagem de produção por turno",
  "Verificar segregação de embalagens danificadas",
  "Verificar ventilação da área de embalagem",
  "Verificar condição da pistola de calor (shrink)",
  "Verificar qualidade da impressão nas caixas",
  "Verificar separação por modelo/destino",
  "Verificar envio para expedição (registro)",
];

const itensAlmoxarifado = [
  "Verificar recebimento do material (nota fiscal x pedido)",
  "Verificar conferência quantitativa do material",
  "Verificar inspeção visual do material recebido",
  "Verificar laudo/certificado do fornecedor",
  "Verificar rastreabilidade do lote recebido",
  "Verificar identificação do material no estoque",
  "Verificar local de armazenamento correto",
  "Verificar empilhamento máximo permitido",
  "Verificar condições de armazenagem (temperatura e umidade)",
  "Verificar separação de materiais por tipo/classe",
  "Verificar FIFO (primeiro a entrar, primeiro a sair)",
  "Verificar validade dos materiais perecíveis",
  "Verificar materiais químicos com FISPQ disponível",
  "Verificar segregação de materiais não conformes",
  "Verificar materiais bloqueados/quarentena identificados",
  "Verificar liberação de materiais aprovados pela qualidade",
  "Verificar registro de entrada no sistema",
  "Verificar registro de saída/requisição no sistema",
  "Verificar inventário cíclico em dia",
  "Verificar acuracidade de estoque",
  "Verificar organização geral do almoxarifado",
  "Verificar limpeza do almoxarifado",
  "Verificar sinalização das áreas/prateleiras",
  "Verificar condição das prateleiras/estantes",
  "Verificar iluminação adequada",
  "Verificar combate a pragas (insetos/roedores)",
  "Verificar extintores de incêndio (validade e acesso)",
  "Verificar EPI dos operadores",
  "Verificar equipamentos de movimentação (empilhadeira, paleteira)",
  "Verificar condição dos paletes",
  "Verificar controle de acesso ao almoxarifado",
  "Verificar descarte correto de embalagens",
  "Verificar devoluções processadas",
  "Verificar manutenção preventiva dos equipamentos",
  "Verificar sistema de ventilação",
  "Verificar integridade das embalagens armazenadas",
  "Verificar registro de avarias no recebimento",
  "Verificar endereçamento correto no sistema",
  "Verificar separação de itens de alto valor/controle especial",
  "Verificar documentação de rastreabilidade completa",
];

const itensEstofamento = [
  "Verificar tipo de espuma conforme especificação do modelo",
  "Verificar densidade da espuma utilizada",
  "Verificar dimensões da espuma cortada para estofamento",
  "Verificar tipo de manta/fibra aplicada",
  "Verificar colagem da espuma na estrutura",
  "Verificar tipo de cola utilizada (atóxica)",
  "Verificar fixação da espuma (sem descolamento)",
  "Verificar preenchimento uniforme do estofado",
  "Verificar ausência de irregularidades/calombos",
  "Verificar conforto ao sentar/deitar",
  "Verificar firmeza conforme classificação do modelo",
  "Verificar perfilamento da espuma (se aplicável)",
  "Verificar aplicação de tecido/revestimento",
  "Verificar tensão do tecido sobre a espuma",
  "Verificar grampeamento/fixação do tecido na estrutura",
  "Verificar costura do revestimento",
  "Verificar acabamento de costuras visíveis",
  "Verificar zíper de capa removível (se aplicável)",
  "Verificar capitonê/botões (se aplicável)",
  "Verificar simetria do estofamento",
  "Verificar aspecto visual final",
  "Verificar etiqueta de composição",
  "Verificar identificação do produto",
  "Verificar EPI dos operadores",
  "Verificar limpeza da área de estofamento",
  "Verificar condição da grampeadeira",
  "Verificar pressão do ar comprimido",
  "Verificar manutenção preventiva dos equipamentos",
  "Verificar registro de produção",
  "Verificar aprovação do inspetor",
  "Verificar segregação de peças não conformes",
  "Verificar rastreabilidade do lote de espuma e tecido",
  "Verificar conformidade com amostra/protótipo",
  "Verificar armazenamento do produto estofado",
  "Verificar envio para próxima etapa",
];

const itensEmbalagemBase = [
  "Verificar base/estrado conforme especificação do modelo",
  "Verificar dimensões da base (comprimento)",
  "Verificar dimensões da base (largura)",
  "Verificar dimensões da base (altura)",
  "Verificar esquadro da base",
  "Verificar estrutura da base (reforço, travessas)",
  "Verificar acabamento da superfície da base",
  "Verificar pés/rodízios instalados (se aplicável)",
  "Verificar nivelamento dos pés",
  "Verificar resistência da base (teste de carga)",
  "Verificar tecido de revestimento da base",
  "Verificar cor do tecido conforme padrão",
  "Verificar grampeamento do tecido na base",
  "Verificar acabamento do fundo da base",
  "Verificar etiqueta de identificação aplicada",
  "Verificar código de barras aplicado",
  "Verificar embalagem de proteção da base",
  "Verificar plástico stretch aplicado",
  "Verificar cantoneiras de proteção",
  "Verificar selagem da embalagem",
  "Verificar peso do produto embalado",
  "Verificar empilhamento máximo respeitado",
  "Verificar paletização correta",
  "Verificar rastreabilidade do lote",
  "Verificar registro de produção/embalagem",
  "Verificar limpeza do produto antes de embalar",
  "Verificar ausência de defeitos visuais",
  "Verificar manual de instruções incluído",
  "Verificar garantia incluída na embalagem",
  "Verificar aprovação do inspetor de qualidade",
  "Verificar liberação para expedição",
  "Verificar limpeza da área de trabalho",
  "Verificar EPI dos operadores",
  "Verificar condição dos equipamentos de embalagem",
  "Verificar manutenção preventiva em dia",
  "Verificar descarte correto de resíduos de embalagem",
  "Verificar conformidade com pedido de venda",
  "Verificar contagem de peças embaladas",
  "Verificar armazenamento temporário adequado",
  "Verificar documentação de expedição",
];

const ITENS_POR_SETOR: Record<string, string[]> = {
  "ESPUMAÇÃO": itensEspumacao,
  "ÁREA DE CURA": itensAreaCura,
  "FLOCADEIRA": itensFlocadeira,
  "LAMINAÇÃO": itensLaminacao,
  "MOLA": itensMola,
  "BORDADEIRA": itensBordadeira,
  "CORTE E COSTURA": itensCorteECostura,
  "MARCENARIA": itensMarcenaria,
  "TAPEÇARIA": itensTapecaria,
  "FECHAMENTO": itensFechamento,
  "MÓVEIS": itensMoveis,
  "EMBALAGEM": itensEmbalagem,
  "ALMOXARIFADO": itensAlmoxarifado,
  "ESTOFAMENTO": itensEstofamento,
  "EMBALAGEM DE BASE": itensEmbalagemBase,
};

// ── TIPOS DE NC REAIS POR SETOR (~167) ──
const TIPOS_NC_POR_SETOR: Record<string, { nome: string; categoria: string }[]> = {
  "ESPUMAÇÃO": [
    { nome: "Densidade fora da especificação", categoria: "Dimensional" },
    { nome: "Bolhas na espuma", categoria: "Visual" },
    { nome: "Buracos internos", categoria: "Visual" },
    { nome: "Cor não uniforme", categoria: "Visual" },
    { nome: "Altura do bloco fora do padrão", categoria: "Dimensional" },
    { nome: "Odor forte residual", categoria: "Funcional" },
    { nome: "Dosagem incorreta de químico", categoria: "Processo" },
    { nome: "Temperatura fora do range", categoria: "Processo" },
    { nome: "Tempo de cura insuficiente", categoria: "Processo" },
    { nome: "Contaminação do material", categoria: "Material" },
    { nome: "Bloco com deformação", categoria: "Dimensional" },
    { nome: "Espuma quebradiça", categoria: "Funcional" },
    { nome: "Reação incompleta", categoria: "Processo" },
  ],
  "ÁREA DE CURA": [
    { nome: "Cura incompleta", categoria: "Processo" },
    { nome: "Deformação durante cura", categoria: "Dimensional" },
    { nome: "Temperatura inadequada", categoria: "Processo" },
    { nome: "Umidade fora do padrão", categoria: "Processo" },
    { nome: "Tempo de cura insuficiente", categoria: "Processo" },
    { nome: "Bloco contaminado na cura", categoria: "Material" },
    { nome: "Identificação de lote incorreta", categoria: "Documentação" },
    { nome: "FIFO não respeitado", categoria: "Processo" },
  ],
  "FLOCADEIRA": [
    { nome: "Flocos com tamanho irregular", categoria: "Dimensional" },
    { nome: "Contaminação nos flocos", categoria: "Material" },
    { nome: "Mistura indevida de densidades", categoria: "Processo" },
    { nome: "Peso fora da especificação", categoria: "Dimensional" },
    { nome: "Lâmina desalinhada", categoria: "Processo" },
    { nome: "Filtros sujos não substituídos", categoria: "Limpeza" },
    { nome: "Aspiração insuficiente", categoria: "Segurança" },
    { nome: "Material com resíduos", categoria: "Material" },
  ],
  "LAMINAÇÃO": [
    { nome: "Espessura fora da tolerância", categoria: "Dimensional" },
    { nome: "Ondulação na superfície", categoria: "Visual" },
    { nome: "Rasgo na lâmina", categoria: "Visual" },
    { nome: "Marcas na superfície cortada", categoria: "Visual" },
    { nome: "Corte fora de esquadro", categoria: "Dimensional" },
    { nome: "Lâmina com variação de espessura", categoria: "Dimensional" },
    { nome: "Medição incorreta registrada", categoria: "Documentação" },
    { nome: "Mistura de densidades no lote", categoria: "Processo" },
    { nome: "Perpendicularidade inadequada", categoria: "Dimensional" },
    { nome: "Acabamento de superfície ruim", categoria: "Visual" },
  ],
  "MOLA": [
    { nome: "Altura da mola fora do padrão", categoria: "Dimensional" },
    { nome: "Diâmetro fora da especificação", categoria: "Dimensional" },
    { nome: "Número de espiras incorreto", categoria: "Dimensional" },
    { nome: "Força de compressão inadequada", categoria: "Funcional" },
    { nome: "Mola deformada", categoria: "Visual" },
    { nome: "TNT furado pela mola", categoria: "Material" },
    { nome: "Solda de arame fraca", categoria: "Funcional" },
    { nome: "Painel fora de esquadro", categoria: "Dimensional" },
    { nome: "Mola solta no painel", categoria: "Funcional" },
    { nome: "Ruído excessivo ao comprimir", categoria: "Funcional" },
    { nome: "Bitola do arame incorreta", categoria: "Material" },
    { nome: "Tratamento térmico inadequado", categoria: "Processo" },
    { nome: "Ensacamento invertido", categoria: "Processo" },
    { nome: "Gramatura do TNT fora do padrão", categoria: "Material" },
    { nome: "Dureza fora da especificação", categoria: "Funcional" },
  ],
  "BORDADEIRA": [
    { nome: "Bordado desalinhado", categoria: "Visual" },
    { nome: "Pontos pulados", categoria: "Visual" },
    { nome: "Linha solta/rompida", categoria: "Visual" },
    { nome: "Cor da linha incorreta", categoria: "Visual" },
    { nome: "Padrão de bordado incorreto", categoria: "Processo" },
    { nome: "Enrugamento do tecido", categoria: "Visual" },
    { nome: "Dimensão do bordado fora do padrão", categoria: "Dimensional" },
    { nome: "Logo posicionado incorretamente", categoria: "Visual" },
    { nome: "Acabamento ruim nas pontas", categoria: "Visual" },
    { nome: "Tensão da linha incorreta", categoria: "Processo" },
  ],
  "CORTE E COSTURA": [
    { nome: "Corte fora das dimensões", categoria: "Dimensional" },
    { nome: "Costura torta/desviada", categoria: "Visual" },
    { nome: "Pontos pulados na costura", categoria: "Visual" },
    { nome: "Desfiamento no tecido", categoria: "Visual" },
    { nome: "Tecido com defeito (furo/mancha)", categoria: "Material" },
    { nome: "Zíper com defeito", categoria: "Funcional" },
    { nome: "Etiqueta mal posicionada", categoria: "Visual" },
    { nome: "Mancha de óleo de máquina", categoria: "Limpeza" },
    { nome: "Elástico mal posicionado", categoria: "Visual" },
    { nome: "Ponto por cm fora do padrão", categoria: "Dimensional" },
    { nome: "Emenda não permitida", categoria: "Processo" },
    { nome: "Estampa desalinhada", categoria: "Visual" },
    { nome: "Peça com medida incorreta", categoria: "Dimensional" },
    { nome: "Cor do tecido divergente", categoria: "Material" },
    { nome: "Resistência da costura insuficiente", categoria: "Funcional" },
  ],
  "MARCENARIA": [
    { nome: "Peça fora de esquadro", categoria: "Dimensional" },
    { nome: "Dimensões incorretas", categoria: "Dimensional" },
    { nome: "Lascas/trincas nas bordas", categoria: "Visual" },
    { nome: "Furação deslocada", categoria: "Dimensional" },
    { nome: "Fita de borda mal aplicada", categoria: "Visual" },
    { nome: "Excesso de cola aparente", categoria: "Visual" },
    { nome: "Pintura com escorrimento", categoria: "Visual" },
    { nome: "Cor da pintura divergente", categoria: "Visual" },
    { nome: "Ferragem mal encaixada", categoria: "Funcional" },
    { nome: "Gaveta/porta desalinhada", categoria: "Funcional" },
    { nome: "Umidade da madeira acima do padrão", categoria: "Material" },
    { nome: "Superfície não lixada adequadamente", categoria: "Visual" },
  ],
  "TAPEÇARIA": [
    { nome: "Tecido com rugas", categoria: "Visual" },
    { nome: "Grampeamento irregular", categoria: "Visual" },
    { nome: "Revestimento desalinhado", categoria: "Visual" },
    { nome: "Tecido com furo/rasgo", categoria: "Material" },
    { nome: "Cor do tecido divergente", categoria: "Material" },
    { nome: "Estofamento irregular (calombo)", categoria: "Visual" },
    { nome: "Costura aparente mal acabada", categoria: "Visual" },
    { nome: "Capitonê mal posicionado", categoria: "Visual" },
    { nome: "Tensão do tecido irregular", categoria: "Processo" },
    { nome: "Conforto inadequado ao sentar", categoria: "Funcional" },
    { nome: "Simetria comprometida", categoria: "Visual" },
  ],
  "FECHAMENTO": [
    { nome: "Espuma descolada da mola", categoria: "Funcional" },
    { nome: "Colchão fora de esquadro", categoria: "Dimensional" },
    { nome: "Dimensão final fora da tolerância", categoria: "Dimensional" },
    { nome: "Viés lateral solto", categoria: "Visual" },
    { nome: "Alça mal fixada", categoria: "Funcional" },
    { nome: "Válvula de ar com defeito", categoria: "Funcional" },
    { nome: "Ponto duro ao deitar", categoria: "Funcional" },
    { nome: "Etiqueta ausente ou incorreta", categoria: "Documentação" },
    { nome: "Costura de fechamento irregular", categoria: "Visual" },
    { nome: "Manta com gramatura incorreta", categoria: "Material" },
    { nome: "Pillow top com preenchimento irregular", categoria: "Visual" },
    { nome: "Firmeza fora da classificação", categoria: "Funcional" },
    { nome: "Mancha/sujeira no produto", categoria: "Limpeza" },
    { nome: "Odor desagradável", categoria: "Funcional" },
  ],
  "MÓVEIS": [
    { nome: "Acabamento com riscos/arranhões", categoria: "Visual" },
    { nome: "Cor fora do padrão", categoria: "Visual" },
    { nome: "Estrutura com folga", categoria: "Funcional" },
    { nome: "Revestimento mal aplicado", categoria: "Visual" },
    { nome: "Costura do estofado com defeito", categoria: "Visual" },
    { nome: "Mecanismo recliner com defeito", categoria: "Funcional" },
    { nome: "Pés desnivelados", categoria: "Funcional" },
    { nome: "Rebarbas/pontas afiadas", categoria: "Segurança" },
    { nome: "Ferragem mal fixada", categoria: "Funcional" },
    { nome: "Dimensões fora do projeto", categoria: "Dimensional" },
    { nome: "Kit de montagem incompleto", categoria: "Documentação" },
  ],
  "EMBALAGEM": [
    { nome: "Produto danificado durante embalagem", categoria: "Visual" },
    { nome: "Embalagem rasgada/furada", categoria: "Material" },
    { nome: "Etiqueta incorreta/ausente", categoria: "Documentação" },
    { nome: "Código de barras ilegível", categoria: "Documentação" },
    { nome: "Selagem incompleta", categoria: "Processo" },
    { nome: "Cantoneira mal posicionada", categoria: "Processo" },
    { nome: "Paletização incorreta", categoria: "Processo" },
    { nome: "Empilhamento acima do limite", categoria: "Segurança" },
    { nome: "Acessórios faltando na embalagem", categoria: "Documentação" },
    { nome: "Vácuo insuficiente (bed-in-a-box)", categoria: "Processo" },
  ],
  "ALMOXARIFADO": [
    { nome: "Quantidade recebida divergente da NF", categoria: "Processo" },
    { nome: "Material com defeito no recebimento", categoria: "Material" },
    { nome: "Laudo do fornecedor ausente", categoria: "Documentação" },
    { nome: "Armazenamento em local incorreto", categoria: "Processo" },
    { nome: "Material sem identificação", categoria: "Documentação" },
    { nome: "FIFO não respeitado", categoria: "Processo" },
    { nome: "Material vencido no estoque", categoria: "Material" },
    { nome: "FISPQ não disponível", categoria: "Documentação" },
    { nome: "Condições de armazenagem inadequadas", categoria: "Processo" },
    { nome: "Avaria no estoque", categoria: "Material" },
    { nome: "Acuracidade do estoque fora do padrão", categoria: "Processo" },
  ],
  "ESTOFAMENTO": [
    { nome: "Espuma com densidade incorreta", categoria: "Material" },
    { nome: "Preenchimento irregular", categoria: "Visual" },
    { nome: "Cola com aderência insuficiente", categoria: "Funcional" },
    { nome: "Tecido com tensão irregular", categoria: "Visual" },
    { nome: "Grampeamento visível/saliente", categoria: "Visual" },
    { nome: "Simetria do estofado comprometida", categoria: "Visual" },
    { nome: "Conforto fora do padrão", categoria: "Funcional" },
    { nome: "Zíper da capa travado", categoria: "Funcional" },
    { nome: "Capitonê desalinhado", categoria: "Visual" },
    { nome: "Calombo na superfície", categoria: "Visual" },
  ],
  "EMBALAGEM DE BASE": [
    { nome: "Base fora de esquadro", categoria: "Dimensional" },
    { nome: "Dimensões incorretas da base", categoria: "Dimensional" },
    { nome: "Pés/rodízios soltos", categoria: "Funcional" },
    { nome: "Revestimento com defeito", categoria: "Visual" },
    { nome: "Embalagem rasgada", categoria: "Material" },
    { nome: "Etiqueta incorreta/ausente", categoria: "Documentação" },
    { nome: "Base com resistência insuficiente", categoria: "Funcional" },
    { nome: "Acabamento do fundo irregular", categoria: "Visual" },
    { nome: "Cor do tecido divergente", categoria: "Material" },
    { nome: "Manual não incluído", categoria: "Documentação" },
  ],
  "Geral": [
    { nome: "EPI não utilizado", categoria: "Segurança" },
    { nome: "Limpeza inadequada da área", categoria: "Limpeza" },
    { nome: "Manutenção preventiva atrasada", categoria: "Processo" },
    { nome: "Registro de produção não preenchido", categoria: "Documentação" },
    { nome: "Instrumento de medição não calibrado", categoria: "Processo" },
    { nome: "Iluminação inadequada", categoria: "Segurança" },
    { nome: "Sinalização de segurança ausente", categoria: "Segurança" },
    { nome: "Rastreabilidade do lote incompleta", categoria: "Documentação" },
    { nome: "Segregação de material não conforme ausente", categoria: "Processo" },
    { nome: "Outro (especificar)", categoria: "Processo" },
  ],
};

// ── 16 PADRÕES REAIS DE MOLA ──
const PADROES_MOLA_REAIS = [
  { alturaTipo: "130", item: "Diâmetro do arame", descricao: "Bitola do arame de aço", padrao: 1.80, minimo: 1.75, maximo: 1.85, unidade: "mm" },
  { alturaTipo: "130", item: "Altura livre", descricao: "Altura da mola sem carga", padrao: 130, minimo: 127, maximo: 133, unidade: "mm" },
  { alturaTipo: "130", item: "Diâmetro externo", descricao: "Diâmetro externo da mola", padrao: 60, minimo: 58, maximo: 62, unidade: "mm" },
  { alturaTipo: "130", item: "Número de espiras", descricao: "Quantidade de espiras ativas", padrao: 5.5, minimo: 5.0, maximo: 6.0, unidade: "un" },
  { alturaTipo: "130", item: "Força 25%", descricao: "Força de compressão a 25% de deflexão", padrao: 1.20, minimo: 1.00, maximo: 1.40, unidade: "kgf" },
  { alturaTipo: "130", item: "Força 50%", descricao: "Força de compressão a 50% de deflexão", padrao: 2.80, minimo: 2.50, maximo: 3.10, unidade: "kgf" },
  { alturaTipo: "130", item: "Força 75%", descricao: "Força de compressão a 75% de deflexão", padrao: 5.50, minimo: 5.00, maximo: 6.00, unidade: "kgf" },
  { alturaTipo: "130", item: "Passo da mola", descricao: "Distância entre espiras consecutivas", padrao: 23.6, minimo: 22.5, maximo: 24.7, unidade: "mm" },
  { alturaTipo: "200", item: "Diâmetro do arame", descricao: "Bitola do arame de aço", padrao: 2.00, minimo: 1.95, maximo: 2.05, unidade: "mm" },
  { alturaTipo: "200", item: "Altura livre", descricao: "Altura da mola sem carga", padrao: 200, minimo: 196, maximo: 204, unidade: "mm" },
  { alturaTipo: "200", item: "Diâmetro externo", descricao: "Diâmetro externo da mola", padrao: 65, minimo: 63, maximo: 67, unidade: "mm" },
  { alturaTipo: "200", item: "Número de espiras", descricao: "Quantidade de espiras ativas", padrao: 7.5, minimo: 7.0, maximo: 8.0, unidade: "un" },
  { alturaTipo: "200", item: "Força 25%", descricao: "Força de compressão a 25% de deflexão", padrao: 1.80, minimo: 1.50, maximo: 2.10, unidade: "kgf" },
  { alturaTipo: "200", item: "Força 50%", descricao: "Força de compressão a 50% de deflexão", padrao: 4.20, minimo: 3.80, maximo: 4.60, unidade: "kgf" },
  { alturaTipo: "200", item: "Força 75%", descricao: "Força de compressão a 75% de deflexão", padrao: 8.50, minimo: 7.80, maximo: 9.20, unidade: "kgf" },
  { alturaTipo: "200", item: "Passo da mola", descricao: "Distância entre espiras consecutivas", padrao: 28.6, minimo: 27.5, maximo: 29.7, unidade: "mm" },
];

// ── SEED FUNCTION ──
export function seedInspecoesData() {
  // Only seed if collections are empty
  if (db.inspecoesModelos.length > 0) return;

  const now = new Date().toISOString();
  let ncCounter = 0;
  let pmCounter = 0;

  // 1. Seed modelos (1 per sector with all real items)
  for (const setor of SETORES_REAIS) {
    const itensDesc = ITENS_POR_SETOR[setor] || [];
    _itemCounter = 0;
    const itens = itensDesc.map((desc, idx) => makeItem(desc, idx + 1));

    db.inspecoesModelos.push({
      id: `MOD-${setor.replace(/\s+/g, "-").replace(/[^A-Z0-9-]/gi, "")}`,
      nome: `Checklist ${setor}`,
      setor,
      descricao: `Checklist de inspeção de qualidade — setor ${setor}`,
      ativo: true,
      ordem: SETORES_REAIS.indexOf(setor) + 1,
      itens,
      createdAt: now,
      updatedAt: now,
    });
  }

  // 2. Seed tipos NC (all real types by sector)
  for (const [setor, tipos] of Object.entries(TIPOS_NC_POR_SETOR)) {
    for (const t of tipos) {
      db.inspecoesTiposNc.push({
        id: `TNC-${String(++ncCounter).padStart(3, "0")}`,
        setor,
        nome: t.nome,
        categoria: t.categoria,
        ativo: true,
      });
    }
  }

  // 3. Seed padrões de mola (16 real patterns)
  for (const p of PADROES_MOLA_REAIS) {
    db.inspecoesPadroesMola.push({
      id: `PM-${String(++pmCounter).padStart(3, "0")}`,
      ...p,
      ativo: true,
    });
  }

  // 4. Seed default user-sector mappings for ADMIN (all sectors)
  const adminUsers = db.usuarios.filter((u: any) => u.perfil === "ADMIN");
  for (const u of adminUsers) {
    for (const setor of SETORES_REAIS) {
      db.inspecoesUsuarioSetor.push({
        id: `US-${randomUUID().slice(0, 8)}`,
        userId: u.id,
        setor,
      });
    }
  }
  // QUALIDADE users also get all sectors
  const qualUsers = db.usuarios.filter((u: any) => u.perfil === "QUALIDADE");
  for (const u of qualUsers) {
    for (const setor of SETORES_REAIS) {
      db.inspecoesUsuarioSetor.push({
        id: `US-${randomUUID().slice(0, 8)}`,
        userId: u.id,
        setor,
      });
    }
  }

  console.log(`[seed] Inspeções: ${db.inspecoesModelos.length} modelos, ${db.inspecoesTiposNc.length} tipos NC, ${db.inspecoesPadroesMola.length} padrões mola carregados.`);
}
