// Seed data for assistência terceirizada backend routes (mirrors frontend mocks)
export const mockAssistenciasTerceirizadas = [
  { id: "AT-001", nome: "TechRepair Ltda", razaoSocial: "TechRepair Serviços Técnicos Ltda", cnpjCpf: "12.345.678/0001-90", contatoPrincipal: "Carlos Mendes", telefone: "(92) 99123-4567", email: "contato@techrepair.com.br", endereco: "Rua Industrial, 450", cidade: "Manaus", uf: "AM", status: "ATIVA", criadoAt: "2025-06-10", atualizadoAt: "2026-01-15" },
  { id: "AT-002", nome: "MaqConserto", razaoSocial: "MaqConserto Assistência Técnica ME", cnpjCpf: "98.765.432/0001-10", contatoPrincipal: "Ana Souza", telefone: "(91) 98765-1234", email: "ana@maqconserto.com.br", endereco: "Av. Augusto Montenegro, 1200", cidade: "Belém", uf: "PA", status: "ATIVA", criadoAt: "2025-08-20", atualizadoAt: "2026-02-10" },
  { id: "AT-003", nome: "ElétriServ", razaoSocial: "ElétriServ Manutenção Eireli", cnpjCpf: "55.667.788/0001-33", contatoPrincipal: "Roberto Lima", telefone: "(92) 3234-5678", email: "roberto@eletriserv.com.br", endereco: "Distrito Industrial, Q10 L5", cidade: "Manaus", uf: "AM", observacoes: "Especializada em motores e painéis elétricos", status: "INATIVA", criadoAt: "2025-04-01", atualizadoAt: "2025-12-01" },
];

export const mockItensEmAssistencia = [
  { id: "IA-001", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoItem: "EQUIPAMENTO", codigoItem: "EQP-COSTURA-01", descricao: "Máquina de Costura Industrial Juki DDL-8700", numeroSerie: "JK-2024-00145", patrimonio: "PAT-00312", quantidade: 1, quantidadeRetornada: 0, defeito: "Motor principal com ruído excessivo e travamento intermitente", osReferencia: "OS-001", status: "EM_REPARO", responsavelEnvio: "João Técnico", dataEnvio: "2026-02-28" },
  { id: "IA-002", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoItem: "PECA", codigoItem: "MAT-003", descricao: "Mola Bonnel Casal", quantidade: 5, quantidadeRetornada: 0, defeito: "Molas com deformação — envio para verificação de lote", status: "EM_ANALISE", responsavelEnvio: "Maria Técnica", dataEnvio: "2026-03-05" },
  { id: "IA-003", assistenciaId: "AT-002", assistenciaNome: "MaqConserto", tipoItem: "EQUIPAMENTO", codigoItem: "EQP-CORTE-02", descricao: "Máquina de Corte CNC Fabric Cutter 3000", numeroSerie: "FC-2023-00089", patrimonio: "PAT-00287", quantidade: 1, quantidadeRetornada: 0, defeito: "Falha na calibração do eixo X — corte desalinhado", osReferencia: "OS-002", status: "AGUARDANDO_PECA", responsavelEnvio: "Carlos Técnico", dataEnvio: "2026-02-20" },
  { id: "IA-004", assistenciaId: "AT-002", assistenciaNome: "MaqConserto", tipoItem: "PECA", codigoItem: "MAT-007", descricao: "Cola Spray Industrial", quantidade: 10, quantidadeRetornada: 10, defeito: "Lote com pressão irregular — enviado para laudo", status: "DEVOLVIDO", responsavelEnvio: "Pedro Instalador", dataEnvio: "2026-02-10", dataRetorno: "2026-02-25", observacao: "Laudo confirmou problema no lote. Fornecedor notificado." },
  { id: "IA-005", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoItem: "EQUIPAMENTO", codigoItem: "EQP-EMBALA-03", descricao: "Seladora Automática Selapak 200", numeroSerie: "SP-2025-00201", patrimonio: "PAT-00401", quantidade: 1, quantidadeRetornada: 1, defeito: "Resistência de selagem queimada", status: "CONSERTADO", responsavelEnvio: "Ana Inspetora", dataEnvio: "2026-01-15", dataRetorno: "2026-02-05", observacao: "Resistência substituída e calibrada" },
];

export const mockMovimentacoes = [
  { id: "MOV-001", itemId: "IA-001", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoMovimentacao: "ENVIO_EQUIPAMENTO", codigoItem: "EQP-COSTURA-01", descricaoItem: "Máquina de Costura Industrial Juki DDL-8700", quantidade: 1, status: "ENVIADO", usuario: "João Técnico", dataHora: "2026-02-28T10:30:00" },
  { id: "MOV-002", itemId: "IA-002", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoMovimentacao: "ENVIO_PECA", codigoItem: "MAT-003", descricaoItem: "Mola Bonnel Casal", quantidade: 5, status: "ENVIADO", usuario: "Maria Técnica", dataHora: "2026-03-05T14:15:00" },
  { id: "MOV-003", itemId: "IA-003", assistenciaId: "AT-002", assistenciaNome: "MaqConserto", tipoMovimentacao: "ENVIO_EQUIPAMENTO", codigoItem: "EQP-CORTE-02", descricaoItem: "Máquina de Corte CNC Fabric Cutter 3000", quantidade: 1, status: "ENVIADO", usuario: "Carlos Técnico", dataHora: "2026-02-20T08:00:00" },
  { id: "MOV-004", itemId: "IA-004", assistenciaId: "AT-002", assistenciaNome: "MaqConserto", tipoMovimentacao: "ENVIO_PECA", codigoItem: "MAT-007", descricaoItem: "Cola Spray Industrial", quantidade: 10, status: "ENVIADO", usuario: "Pedro Instalador", dataHora: "2026-02-10T09:00:00" },
  { id: "MOV-005", itemId: "IA-004", assistenciaId: "AT-002", assistenciaNome: "MaqConserto", tipoMovimentacao: "RETORNO_PECA", codigoItem: "MAT-007", descricaoItem: "Cola Spray Industrial", quantidade: 10, status: "DEVOLVIDO", usuario: "Pedro Instalador", dataHora: "2026-02-25T16:30:00", condicaoRetorno: "SEM_DEFEITO", laudoObservacao: "Pressão irregular confirmada pelo fornecedor. Lote substituído." },
  { id: "MOV-006", itemId: "IA-005", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoMovimentacao: "ENVIO_EQUIPAMENTO", codigoItem: "EQP-EMBALA-03", descricaoItem: "Seladora Automática Selapak 200", quantidade: 1, status: "ENVIADO", usuario: "Ana Inspetora", dataHora: "2026-01-15T11:00:00" },
  { id: "MOV-007", itemId: "IA-005", assistenciaId: "AT-001", assistenciaNome: "TechRepair Ltda", tipoMovimentacao: "RETORNO_EQUIPAMENTO", codigoItem: "EQP-EMBALA-03", descricaoItem: "Seladora Automática Selapak 200", quantidade: 1, status: "CONSERTADO", usuario: "Ana Inspetora", dataHora: "2026-02-05T14:00:00", condicaoRetorno: "CONSERTADO", laudoObservacao: "Resistência substituída e calibrada. Equipamento em perfeito funcionamento." },
];
