-- =====================================================================
-- DDL — Módulo Inspeções — Tabelas Normalizadas Oracle
-- =====================================================================

-- 1. Setores
CREATE TABLE INS_SETOR (
  ID            VARCHAR2(40)  PRIMARY KEY,
  NOME          VARCHAR2(120) NOT NULL,
  ORDEM         NUMBER(4)     NOT NULL,
  ATIVO         NUMBER(1)     DEFAULT 1 NOT NULL,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. Usuário ↔ Setor
CREATE TABLE INS_USUARIO_SETOR (
  ID            VARCHAR2(40)  PRIMARY KEY,
  USER_ID       VARCHAR2(80)  NOT NULL,
  SETOR_ID      VARCHAR2(40)  NOT NULL REFERENCES INS_SETOR(ID),
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_INS_US_USER ON INS_USUARIO_SETOR(USER_ID);

-- 3. Modelo de Checklist (um por setor)
CREATE TABLE INS_MODELO_CHECKLIST (
  ID            VARCHAR2(40)  PRIMARY KEY,
  NOME          VARCHAR2(200) NOT NULL,
  SETOR_ID      VARCHAR2(40)  NOT NULL REFERENCES INS_SETOR(ID),
  DESCRICAO     VARCHAR2(500),
  ATIVO         NUMBER(1)     DEFAULT 1 NOT NULL,
  ORDEM         NUMBER(4)     NOT NULL,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- 4. Item do Checklist
CREATE TABLE INS_MODELO_CHECKLIST_ITEM (
  ID              VARCHAR2(40)  PRIMARY KEY,
  MODELO_ID       VARCHAR2(40)  NOT NULL REFERENCES INS_MODELO_CHECKLIST(ID),
  DESCRICAO       VARCHAR2(500) NOT NULL,
  ORDEM           NUMBER(4)     NOT NULL,
  OBRIGATORIO     NUMBER(1)     DEFAULT 1 NOT NULL,
  EXIGE_EVIDENCIA NUMBER(1)     DEFAULT 1 NOT NULL,
  EXIGE_TIPO_NC   NUMBER(1)     DEFAULT 1 NOT NULL,
  ATIVO           NUMBER(1)     DEFAULT 1 NOT NULL
);
CREATE INDEX IDX_INS_MCI_MOD ON INS_MODELO_CHECKLIST_ITEM(MODELO_ID);

-- 5. Tipo de NC
CREATE TABLE INS_TIPO_NC (
  ID            VARCHAR2(40)  PRIMARY KEY,
  SETOR_ID      VARCHAR2(40)  REFERENCES INS_SETOR(ID),
  NOME          VARCHAR2(300) NOT NULL,
  CATEGORIA     VARCHAR2(60)  DEFAULT 'Processo',
  ATIVO         NUMBER(1)     DEFAULT 1 NOT NULL
);
CREATE INDEX IDX_INS_TNC_SET ON INS_TIPO_NC(SETOR_ID);

-- 6. Execução de Inspeção
CREATE TABLE INS_EXECUCAO (
  ID              VARCHAR2(40)  PRIMARY KEY,
  MODELO_ID       VARCHAR2(40)  NOT NULL REFERENCES INS_MODELO_CHECKLIST(ID),
  SETOR_ID        VARCHAR2(40)  NOT NULL REFERENCES INS_SETOR(ID),
  INSPETOR        VARCHAR2(120),
  STATUS          VARCHAR2(30)  DEFAULT 'EM_ANDAMENTO',
  DATA_INICIO     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  DATA_FIM        TIMESTAMP,
  OBSERVACOES     VARCHAR2(2000),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- 7. Item da Execução
CREATE TABLE INS_EXECUCAO_ITEM (
  ID              VARCHAR2(40)  PRIMARY KEY,
  EXECUCAO_ID     VARCHAR2(40)  NOT NULL REFERENCES INS_EXECUCAO(ID),
  ITEM_ID         VARCHAR2(40)  NOT NULL REFERENCES INS_MODELO_CHECKLIST_ITEM(ID),
  STATUS          VARCHAR2(30)  NOT NULL, -- CONFORME | NAO_CONFORME | NAO_SE_APLICA
  TIPO_NC_ID      VARCHAR2(40)  REFERENCES INS_TIPO_NC(ID),
  OBSERVACAO      VARCHAR2(1000),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_INS_EI_EXEC ON INS_EXECUCAO_ITEM(EXECUCAO_ID);

-- 8. Evidência do Item
CREATE TABLE INS_EXECUCAO_ITEM_EVIDENCIA (
  ID              VARCHAR2(40)  PRIMARY KEY,
  EXEC_ITEM_ID    VARCHAR2(40)  NOT NULL REFERENCES INS_EXECUCAO_ITEM(ID),
  ARQUIVO_URL     VARCHAR2(500) NOT NULL,
  ARQUIVO_NOME    VARCHAR2(200),
  TIPO_MIME       VARCHAR2(80),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_INS_EIE_EI ON INS_EXECUCAO_ITEM_EVIDENCIA(EXEC_ITEM_ID);

-- 9. Máquinas de Mola
CREATE TABLE INS_MOLA_MAQUINA (
  ID              VARCHAR2(40)  PRIMARY KEY,
  CODIGO          VARCHAR2(20)  NOT NULL UNIQUE,
  DESCRICAO       VARCHAR2(200),
  ATIVO           NUMBER(1)     DEFAULT 1 NOT NULL
);

-- 10. Padrão de Mola
CREATE TABLE INS_MOLA_PADRAO (
  ID              VARCHAR2(40)  PRIMARY KEY,
  ALTURA_TIPO     VARCHAR2(20)  NOT NULL,
  ITEM            VARCHAR2(20),
  DESCRICAO       VARCHAR2(300) NOT NULL,
  PADRAO          VARCHAR2(100),
  MINIMO          NUMBER(10,2)  DEFAULT 0,
  MAXIMO          NUMBER(10,2)  DEFAULT 0,
  UNIDADE         VARCHAR2(40),
  ATIVO           NUMBER(1)     DEFAULT 1 NOT NULL
);

-- 11. Inspeção de Mola
CREATE TABLE INS_MOLA_INSPECAO (
  ID              VARCHAR2(40)  PRIMARY KEY,
  MAQUINA_ID      VARCHAR2(40)  NOT NULL REFERENCES INS_MOLA_MAQUINA(ID),
  INSPETOR        VARCHAR2(120),
  STATUS          VARCHAR2(30)  DEFAULT 'EM_ANDAMENTO',
  MAQUINA_PARADA  NUMBER(1)     DEFAULT 0,
  DATA_INSPECAO   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  OBSERVACOES     VARCHAR2(2000),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- 12. Amostra da Inspeção de Mola
CREATE TABLE INS_MOLA_INSPECAO_AMOSTRA (
  ID              VARCHAR2(40)  PRIMARY KEY,
  INSPECAO_ID     VARCHAR2(40)  NOT NULL REFERENCES INS_MOLA_INSPECAO(ID),
  PADRAO_ID       VARCHAR2(40)  NOT NULL REFERENCES INS_MOLA_PADRAO(ID),
  VALOR_MEDIDO    NUMBER(10,2),
  CONFORME        NUMBER(1),
  OBSERVACAO      VARCHAR2(500),
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX IDX_INS_MIA_INS ON INS_MOLA_INSPECAO_AMOSTRA(INSPECAO_ID);

-- 13. Log de Importação
CREATE TABLE INS_IMPORT_LOG (
  ID                VARCHAR2(40)  PRIMARY KEY,
  DATA_IMPORTACAO   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  SETORES           NUMBER(6)     DEFAULT 0,
  MODELOS           NUMBER(6)     DEFAULT 0,
  ITENS             NUMBER(6)     DEFAULT 0,
  TIPOS_NC          NUMBER(6)     DEFAULT 0,
  PADROES_MOLA      NUMBER(6)     DEFAULT 0,
  MAQUINAS          NUMBER(6)     DEFAULT 0,
  USUARIOS          NUMBER(6)     DEFAULT 0,
  VINCULOS_SETOR    NUMBER(6)     DEFAULT 0,
  ALERTAS           VARCHAR2(4000)
);
