-- ============================================================================
-- INSPECOES - BASELINE OFICIAL (Oracle)
-- Estrutura canonical para modulo Inspecoes.
-- ============================================================================

-- 1) CADASTROS BASE
CREATE TABLE INS_SETOR (
  ID            VARCHAR2(40)    PRIMARY KEY,
  NOME          VARCHAR2(120)   NOT NULL,
  ORDEM         NUMBER(5)       NOT NULL,
  ATIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UX_INS_SETOR_NOME ON INS_SETOR (NOME);

CREATE TABLE INS_USUARIO_SETOR (
  ID            VARCHAR2(60)    PRIMARY KEY,
  USUARIO_ID    VARCHAR2(80)    NOT NULL,
  SETOR_ID      VARCHAR2(40)    NOT NULL,
  ATIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_USUARIO_SETOR_SETOR
    FOREIGN KEY (SETOR_ID) REFERENCES INS_SETOR (ID)
);

CREATE UNIQUE INDEX UX_INS_USUARIO_SETOR_UNQ ON INS_USUARIO_SETOR (USUARIO_ID, SETOR_ID);
CREATE INDEX IDX_INS_USUARIO_SETOR_USUARIO ON INS_USUARIO_SETOR (USUARIO_ID);

-- 2) MODELOS E ITENS
CREATE TABLE INS_MODELO_CHECKLIST (
  ID            VARCHAR2(40)    PRIMARY KEY,
  NOME          VARCHAR2(200)   NOT NULL,
  DESCRICAO     VARCHAR2(1000),
  SETOR_ID      VARCHAR2(40)    NOT NULL,
  ORDEM         NUMBER(6)       DEFAULT 1 NOT NULL,
  ATIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_MODELO_SETOR
    FOREIGN KEY (SETOR_ID) REFERENCES INS_SETOR (ID)
);

CREATE INDEX IDX_INS_MODELO_SETOR ON INS_MODELO_CHECKLIST (SETOR_ID, ATIVO, ORDEM);

CREATE TABLE INS_MODELO_CHECKLIST_ITEM (
  ID              VARCHAR2(40)   PRIMARY KEY,
  MODELO_ID       VARCHAR2(40)   NOT NULL,
  SETOR_ID        VARCHAR2(40)   NOT NULL,
  CODIGO_ITEM     VARCHAR2(40)   NOT NULL,
  ORDEM           NUMBER(6)      NOT NULL,
  DESCRICAO       VARCHAR2(1500) NOT NULL,
  OBRIGATORIO     NUMBER(1)      DEFAULT 1 NOT NULL,
  EXIGE_EVIDENCIA NUMBER(1)      DEFAULT 0 NOT NULL,
  EXIGE_TIPO_NC   NUMBER(1)      DEFAULT 1 NOT NULL,
  ATIVO           NUMBER(1)      DEFAULT 1 NOT NULL,
  CRIADO_EM       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_MCI_MODELO
    FOREIGN KEY (MODELO_ID) REFERENCES INS_MODELO_CHECKLIST (ID),
  CONSTRAINT FK_INS_MCI_SETOR
    FOREIGN KEY (SETOR_ID) REFERENCES INS_SETOR (ID)
);

CREATE UNIQUE INDEX UX_INS_MCI_MODELO_CODIGO ON INS_MODELO_CHECKLIST_ITEM (MODELO_ID, CODIGO_ITEM);
CREATE INDEX IDX_INS_MCI_MODELO_ORDEM ON INS_MODELO_CHECKLIST_ITEM (MODELO_ID, ORDEM);

-- 3) TIPOS DE NC
CREATE TABLE INS_TIPO_NC (
  ID            VARCHAR2(40)    PRIMARY KEY,
  SETOR_ID      VARCHAR2(40)    NOT NULL,
  NOME          VARCHAR2(300)   NOT NULL,
  CATEGORIA     VARCHAR2(100),
  OBSERVACAO    VARCHAR2(2000),
  ATIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_TIPO_NC_SETOR
    FOREIGN KEY (SETOR_ID) REFERENCES INS_SETOR (ID)
);

CREATE UNIQUE INDEX UX_INS_TIPO_NC_SETOR_NOME ON INS_TIPO_NC (SETOR_ID, NOME);

-- 4) EXECUCOES
CREATE TABLE INS_EXECUCAO (
  ID                  VARCHAR2(40)    PRIMARY KEY,
  CODIGO              VARCHAR2(80)    NOT NULL,
  MODELO_ID           VARCHAR2(40)    NOT NULL,
  SETOR_ID            VARCHAR2(40)    NOT NULL,
  EXECUTOR_USUARIO_ID VARCHAR2(80),
  EXECUTOR_NOME       VARCHAR2(200),
  DATA_HORA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  STATUS              VARCHAR2(40)    NOT NULL,
  TOTAL_ITENS         NUMBER(8)       DEFAULT 0 NOT NULL,
  CONFORMES           NUMBER(8)       DEFAULT 0 NOT NULL,
  NAO_CONFORMES       NUMBER(8)       DEFAULT 0 NOT NULL,
  NAO_APLICA          NUMBER(8)       DEFAULT 0 NOT NULL,
  TAXA_CONFORMIDADE   NUMBER(6,2)     DEFAULT 0 NOT NULL,
  OBSERVACAO_GERAL    VARCHAR2(2000),
  CRIADO_EM           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_EXEC_MODELO
    FOREIGN KEY (MODELO_ID) REFERENCES INS_MODELO_CHECKLIST (ID),
  CONSTRAINT FK_INS_EXEC_SETOR
    FOREIGN KEY (SETOR_ID) REFERENCES INS_SETOR (ID)
);

CREATE UNIQUE INDEX UX_INS_EXEC_CODIGO ON INS_EXECUCAO (CODIGO);
CREATE INDEX IDX_INS_EXEC_SETOR_DATA ON INS_EXECUCAO (SETOR_ID, DATA_HORA DESC);

CREATE TABLE INS_EXECUCAO_ITEM (
  ID            VARCHAR2(40)    PRIMARY KEY,
  EXECUCAO_ID    VARCHAR2(40)    NOT NULL,
  MODELO_ITEM_ID VARCHAR2(40)    NOT NULL,
  CODIGO_ITEM    VARCHAR2(40)    NOT NULL,
  ORDEM          NUMBER(6)       NOT NULL,
  DESCRICAO      VARCHAR2(1500)  NOT NULL,
  RESULTADO      VARCHAR2(30)    NOT NULL,
  TIPO_NC_ID     VARCHAR2(40),
  TIPO_NC_NOME   VARCHAR2(300),
  OUTRA_NC       VARCHAR2(1000),
  OBSERVACAO     VARCHAR2(2000),
  CRIADO_EM      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_EI_EXECUCAO
    FOREIGN KEY (EXECUCAO_ID) REFERENCES INS_EXECUCAO (ID),
  CONSTRAINT FK_INS_EI_MODELO_ITEM
    FOREIGN KEY (MODELO_ITEM_ID) REFERENCES INS_MODELO_CHECKLIST_ITEM (ID),
  CONSTRAINT FK_INS_EI_TIPO_NC
    FOREIGN KEY (TIPO_NC_ID) REFERENCES INS_TIPO_NC (ID)
);

CREATE INDEX IDX_INS_EI_EXEC_ORDEM ON INS_EXECUCAO_ITEM (EXECUCAO_ID, ORDEM);

CREATE TABLE INS_EXECUCAO_ITEM_EVIDENCIA (
  ID                VARCHAR2(40)    PRIMARY KEY,
  EXECUCAO_ITEM_ID  VARCHAR2(40)    NOT NULL,
  ORDEM_ARQUIVO     NUMBER(4)       DEFAULT 1 NOT NULL,
  NOME_ARQUIVO      VARCHAR2(255)   NOT NULL,
  URL_ARQUIVO       VARCHAR2(1000),
  REFERENCIA_ARQUIVO VARCHAR2(1000),
  MIME_TYPE         VARCHAR2(120),
  TAMANHO_ARQUIVO   NUMBER(12),
  CRIADO_EM         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_EIE_EXEC_ITEM
    FOREIGN KEY (EXECUCAO_ITEM_ID) REFERENCES INS_EXECUCAO_ITEM (ID)
);

CREATE UNIQUE INDEX UX_INS_EIE_ITEM_ORDEM ON INS_EXECUCAO_ITEM_EVIDENCIA (EXECUCAO_ITEM_ID, ORDEM_ARQUIVO);

-- 5) MOLAS
CREATE TABLE INS_MOLA_MAQUINA (
  ID            VARCHAR2(40)    PRIMARY KEY,
  CODIGO        VARCHAR2(20)    NOT NULL,
  DESCRICAO     VARCHAR2(255),
  ATIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UX_INS_MOLA_MAQUINA_CODIGO ON INS_MOLA_MAQUINA (CODIGO);

CREATE TABLE INS_MOLA_PADRAO (
  ID            VARCHAR2(40)    PRIMARY KEY,
  ALTURA_TIPO   VARCHAR2(40)    NOT NULL,
  ITEM          VARCHAR2(40)    NOT NULL,
  DESCRICAO     VARCHAR2(500)   NOT NULL,
  PADRAO        VARCHAR2(120),
  MINIMO        NUMBER(14,4),
  MAXIMO        NUMBER(14,4),
  UNIDADE       VARCHAR2(60),
  ATIVO         NUMBER(1)       DEFAULT 1 NOT NULL,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UX_INS_MOLA_PADRAO_UNQ ON INS_MOLA_PADRAO (ALTURA_TIPO, ITEM);

CREATE TABLE INS_MOLA_INSPECAO (
  ID                  VARCHAR2(40)    PRIMARY KEY,
  CODIGO              VARCHAR2(80)    NOT NULL,
  MAQUINA_ID          VARCHAR2(40)    NOT NULL,
  MAQUINA_CODIGO      VARCHAR2(20)    NOT NULL,
  STATUS_MAQUINA      VARCHAR2(40)    NOT NULL,
  ALTURA_TIPO         VARCHAR2(40),
  LINHA_POCKET        VARCHAR2(200),
  OPERADOR_USUARIO_ID VARCHAR2(80),
  OPERADOR_NOME       VARCHAR2(200),
  DATA_HORA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  OBSERVACAO_GERAL    VARCHAR2(2000),
  RESULTADO           VARCHAR2(40)    NOT NULL,
  MOTIVO_PARADA       VARCHAR2(2000),
  CRIADO_EM           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_MI_MAQUINA
    FOREIGN KEY (MAQUINA_ID) REFERENCES INS_MOLA_MAQUINA (ID)
);

CREATE UNIQUE INDEX UX_INS_MI_CODIGO ON INS_MOLA_INSPECAO (CODIGO);
CREATE INDEX IDX_INS_MI_MAQUINA_DATA ON INS_MOLA_INSPECAO (MAQUINA_ID, DATA_HORA DESC);

CREATE TABLE INS_MOLA_INSPECAO_AMOSTRA (
  ID            VARCHAR2(40)    PRIMARY KEY,
  INSPECAO_ID   VARCHAR2(40)    NOT NULL,
  PADRAO_ID     VARCHAR2(40)    NOT NULL,
  ITEM          VARCHAR2(40),
  DESCRICAO     VARCHAR2(500),
  PADRAO        VARCHAR2(120),
  MINIMO        NUMBER(14,4),
  MAXIMO        NUMBER(14,4),
  UNIDADE       VARCHAR2(60),
  VALOR_MEDIDO  NUMBER(14,4),
  CONFORME      NUMBER(1),
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_INS_MIA_INSPECAO
    FOREIGN KEY (INSPECAO_ID) REFERENCES INS_MOLA_INSPECAO (ID),
  CONSTRAINT FK_INS_MIA_PADRAO
    FOREIGN KEY (PADRAO_ID) REFERENCES INS_MOLA_PADRAO (ID)
);

CREATE INDEX IDX_INS_MIA_INSPECAO ON INS_MOLA_INSPECAO_AMOSTRA (INSPECAO_ID);

-- 6) AUDITORIA
CREATE TABLE INS_AUDITORIA_IMPORTACAO (
  ID                       VARCHAR2(40)   PRIMARY KEY,
  FONTE_ARQUIVO            VARCHAR2(1000) NOT NULL,
  STATUS                   VARCHAR2(30)   NOT NULL,
  SETORES_IMPORTADOS       NUMBER(10)     DEFAULT 0 NOT NULL,
  MODELOS_IMPORTADOS       NUMBER(10)     DEFAULT 0 NOT NULL,
  ITENS_IMPORTADOS         NUMBER(10)     DEFAULT 0 NOT NULL,
  TIPOS_NC_IMPORTADOS      NUMBER(10)     DEFAULT 0 NOT NULL,
  PADROES_MOLA_IMPORTADOS  NUMBER(10)     DEFAULT 0 NOT NULL,
  VINCULOS_USUARIO_SETOR   NUMBER(10)     DEFAULT 0 NOT NULL,
  LINHAS_IGNORADAS         NUMBER(10)     DEFAULT 0 NOT NULL,
  LOG_RESUMO               CLOB,
  CRIADO_EM                TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE INS_AUDITORIA (
  ID            VARCHAR2(40)    PRIMARY KEY,
  ENTIDADE      VARCHAR2(120)   NOT NULL,
  ENTIDADE_ID   VARCHAR2(120),
  ACAO          VARCHAR2(60)    NOT NULL,
  USUARIO_ID    VARCHAR2(80),
  USUARIO_NOME  VARCHAR2(200),
  DETALHES      CLOB,
  CRIADO_EM     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_INS_AUDITORIA_ENTIDADE ON INS_AUDITORIA (ENTIDADE, CRIADO_EM DESC);
