-- SESMT / SST core schema for Quality Navigator
-- Date: 2026-03-27

CREATE TABLE SESMT_UNIDADE (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(10) NOT NULL,
  NOME VARCHAR2(120) NOT NULL,
  REGIONAL VARCHAR2(80),
  ATIVO NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_SETOR (
  ID VARCHAR2(36) PRIMARY KEY,
  UNIDADE_ID VARCHAR2(36) NOT NULL,
  NOME VARCHAR2(120) NOT NULL,
  RESPONSAVEL VARCHAR2(120),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_SETOR_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID)
);

CREATE TABLE SESMT_FUNCAO (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(30),
  NOME VARCHAR2(120) NOT NULL,
  CARGO VARCHAR2(120),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_COLABORADOR (
  ID VARCHAR2(36) PRIMARY KEY,
  MATRICULA VARCHAR2(40),
  NOME VARCHAR2(140) NOT NULL,
  UNIDADE_ID VARCHAR2(36) NOT NULL,
  SETOR_ID VARCHAR2(36),
  FUNCAO_ID VARCHAR2(36),
  STATUS VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_COLAB_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID),
  CONSTRAINT FK_SESMT_COLAB_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SESMT_SETOR (ID),
  CONSTRAINT FK_SESMT_COLAB_FUNCAO FOREIGN KEY (FUNCAO_ID) REFERENCES SESMT_FUNCAO (ID)
);

CREATE TABLE SESMT_PROFISSIONAL (
  ID VARCHAR2(36) PRIMARY KEY,
  NOME VARCHAR2(140) NOT NULL,
  PERFIL_LEGAL VARCHAR2(60) NOT NULL,
  REGISTRO_PROFISSIONAL VARCHAR2(60),
  UNIDADE_ID VARCHAR2(36),
  JORNADA_HORAS NUMBER(5,2),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_PROF_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID)
);

CREATE TABLE SESMT_REQUISITO_LEGAL (
  ID VARCHAR2(36) PRIMARY KEY,
  NORMA VARCHAR2(40) NOT NULL,
  TITULO VARCHAR2(240) NOT NULL,
  APLICABILIDADE VARCHAR2(60) NOT NULL,
  PERIODICIDADE VARCHAR2(40),
  RESPONSAVEL VARCHAR2(120),
  STATUS VARCHAR2(20) NOT NULL,
  RISCO_DESCUMPRIMENTO VARCHAR2(20),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_RISCO (
  ID VARCHAR2(36) PRIMARY KEY,
  UNIDADE_ID VARCHAR2(36) NOT NULL,
  SETOR_ID VARCHAR2(36),
  NR VARCHAR2(20),
  PERIGO VARCHAR2(300) NOT NULL,
  EVENTO_INDESEJADO VARCHAR2(300),
  CONSEQUENCIA VARCHAR2(300),
  CAUSA VARCHAR2(300),
  RISCO_INERENTE NUMBER(10,2),
  RISCO_RESIDUAL NUMBER(10,2),
  STATUS VARCHAR2(30) NOT NULL,
  RESPONSAVEL VARCHAR2(120),
  REVISAO_AT DATE,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_RISCO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID),
  CONSTRAINT FK_SESMT_RISCO_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SESMT_SETOR (ID)
);

CREATE TABLE SESMT_BARRERA_CONTROLE (
  ID VARCHAR2(36) PRIMARY KEY,
  RISCO_ID VARCHAR2(36) NOT NULL,
  TIPO_CONTROLE VARCHAR2(40) NOT NULL,
  DESCRICAO VARCHAR2(300) NOT NULL,
  EFICACIA NUMBER(5,2),
  STATUS VARCHAR2(30) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_BARR_CONT_RISCO FOREIGN KEY (RISCO_ID) REFERENCES SESMT_RISCO (ID)
);

CREATE TABLE SESMT_PLANO_ACAO (
  ID VARCHAR2(36) PRIMARY KEY,
  RISCO_ID VARCHAR2(36),
  TITULO VARCHAR2(240) NOT NULL,
  DESCRICAO VARCHAR2(500),
  RESPONSAVEL VARCHAR2(120),
  PRAZO DATE,
  CRITICIDADE VARCHAR2(20),
  STATUS VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_PLANO_RISCO FOREIGN KEY (RISCO_ID) REFERENCES SESMT_RISCO (ID)
);

CREATE TABLE SESMT_LAUDO (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(50) NOT NULL,
  TIPO VARCHAR2(60) NOT NULL,
  TITULO VARCHAR2(240) NOT NULL,
  UNIDADE_ID VARCHAR2(36),
  DATA_EMISSAO DATE,
  DATA_VALIDADE DATE,
  STATUS VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_LAUDO_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID)
);

CREATE TABLE SESMT_EPI (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(40) NOT NULL,
  DESCRICAO VARCHAR2(220) NOT NULL,
  CA VARCHAR2(40),
  FORNECEDOR VARCHAR2(140),
  VIDA_UTIL_DIAS NUMBER,
  STATUS VARCHAR2(30) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_EPC (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(40) NOT NULL,
  DESCRICAO VARCHAR2(220) NOT NULL,
  UNIDADE_ID VARCHAR2(36),
  LOCALIDADE VARCHAR2(200),
  CRITICIDADE VARCHAR2(20),
  STATUS VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_EPC_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID)
);

CREATE TABLE SESMT_INSPECAO (
  ID VARCHAR2(36) PRIMARY KEY,
  UNIDADE_ID VARCHAR2(36) NOT NULL,
  TIPO VARCHAR2(80) NOT NULL,
  TITULO VARCHAR2(240) NOT NULL,
  DATA_AGENDADA DATE,
  DATA_EXECUCAO DATE,
  STATUS VARCHAR2(30) NOT NULL,
  RESPONSAVEL VARCHAR2(120),
  CRITICIDADE VARCHAR2(20),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_INSP_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID)
);

CREATE TABLE SESMT_TREINAMENTO (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(50),
  TITULO VARCHAR2(240) NOT NULL,
  NR VARCHAR2(20),
  CARGA_HORARIA NUMBER(8,2),
  VALIDADE_MESES NUMBER,
  STATUS VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_EXAME_OCUPACIONAL (
  ID VARCHAR2(36) PRIMARY KEY,
  COLABORADOR_ID VARCHAR2(36) NOT NULL,
  TIPO VARCHAR2(40) NOT NULL,
  DATA_PREVISTA DATE,
  DATA_REALIZADA DATE,
  RESULTADO VARCHAR2(80),
  CUSTO NUMBER(12,2),
  STATUS VARCHAR2(30),
  LABORATORIO VARCHAR2(140),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_EXAME_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADOR (ID)
);

CREATE TABLE SESMT_ATENDIMENTO_OCUPACIONAL (
  ID VARCHAR2(36) PRIMARY KEY,
  COLABORADOR_ID VARCHAR2(36) NOT NULL,
  TIPO_ATENDIMENTO VARCHAR2(80),
  CID VARCHAR2(20),
  MEDICO_RESPONSAVEL VARCHAR2(140),
  DATA_ATENDIMENTO DATE,
  RESTRICAO_ATIVA NUMBER(1) DEFAULT 0,
  OBSERVACOES VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_ATEND_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADOR (ID)
);

CREATE TABLE SESMT_ACIDENTE (
  ID VARCHAR2(36) PRIMARY KEY,
  UNIDADE_ID VARCHAR2(36),
  COLABORADOR_ID VARCHAR2(36),
  TIPO VARCHAR2(80),
  DATA_OCORRENCIA DATE,
  GRAVIDADE VARCHAR2(20),
  DESCRICAO VARCHAR2(1000),
  STATUS VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_ACID_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID),
  CONSTRAINT FK_SESMT_ACID_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADOR (ID)
);

CREATE TABLE SESMT_TERCEIRO (
  ID VARCHAR2(36) PRIMARY KEY,
  EMPRESA VARCHAR2(180) NOT NULL,
  CONTRATO VARCHAR2(60),
  ESCOPO VARCHAR2(240),
  UNIDADE_ID VARCHAR2(36),
  STATUS VARCHAR2(30),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_TERC_UNIDADE FOREIGN KEY (UNIDADE_ID) REFERENCES SESMT_UNIDADE (ID)
);

CREATE TABLE SESMT_DOCUMENTO_CONTROLADO (
  ID VARCHAR2(36) PRIMARY KEY,
  CODIGO VARCHAR2(50) NOT NULL,
  TITULO VARCHAR2(240) NOT NULL,
  VERSAO VARCHAR2(20),
  VIGENCIA_AT DATE,
  STATUS VARCHAR2(30),
  NR VARCHAR2(20),
  RESPONSAVEL VARCHAR2(120),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_REGISTRO (
  ID VARCHAR2(36) PRIMARY KEY,
  MODULE_KEY VARCHAR2(80) NOT NULL,
  TITULO VARCHAR2(240) NOT NULL,
  DESCRICAO VARCHAR2(1000),
  UNIDADE_CODIGO VARCHAR2(10) NOT NULL,
  STATUS VARCHAR2(30) NOT NULL,
  RESPONSAVEL VARCHAR2(120),
  CRITICIDADE VARCHAR2(20),
  NR VARCHAR2(20),
  PERIODO_INICIO DATE,
  PERIODO_FIM DATE,
  SETOR VARCHAR2(120),
  FUNCAO VARCHAR2(120),
  RISCO_INERENTE NUMBER(10,2),
  RISCO_RESIDUAL NUMBER(10,2),
  CUSTO NUMBER(12,2),
  VENCIMENTO_AT DATE,
  DADOS_SAUDE_SENSIVEIS NUMBER(1) DEFAULT 0,
  CREATED_BY VARCHAR2(120),
  UPDATED_BY VARCHAR2(120),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SESMT_REGISTRO_ANEXO (
  ID VARCHAR2(36) PRIMARY KEY,
  REGISTRO_ID VARCHAR2(36) NOT NULL,
  NOME_ARQUIVO VARCHAR2(260) NOT NULL,
  MIME_TYPE VARCHAR2(120),
  TAMANHO NUMBER,
  CAMINHO VARCHAR2(500),
  CRIADO_POR VARCHAR2(120),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_ANEXO_REGISTRO FOREIGN KEY (REGISTRO_ID) REFERENCES SESMT_REGISTRO (ID)
);

CREATE TABLE SESMT_REGISTRO_EVIDENCIA (
  ID VARCHAR2(36) PRIMARY KEY,
  REGISTRO_ID VARCHAR2(36) NOT NULL,
  TIPO VARCHAR2(60),
  DESCRICAO VARCHAR2(1000),
  DATA_EVIDENCIA DATE,
  RESPONSAVEL VARCHAR2(120),
  ANEXO_ID VARCHAR2(36),
  CRIADO_POR VARCHAR2(120),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SESMT_EVID_REGISTRO FOREIGN KEY (REGISTRO_ID) REFERENCES SESMT_REGISTRO (ID),
  CONSTRAINT FK_SESMT_EVID_ANEXO FOREIGN KEY (ANEXO_ID) REFERENCES SESMT_REGISTRO_ANEXO (ID)
);

CREATE INDEX IDX_SESMT_REG_MODULO ON SESMT_REGISTRO (MODULE_KEY, UNIDADE_CODIGO, STATUS);
CREATE INDEX IDX_SESMT_REG_RESP ON SESMT_REGISTRO (RESPONSAVEL, CRITICIDADE);
CREATE INDEX IDX_SESMT_EXAME_COLAB ON SESMT_EXAME_OCUPACIONAL (COLABORADOR_ID, DATA_PREVISTA);

