import { randomUUID } from "node:crypto";
import { executeOracle, isOracleEnabled } from "../../db/oracle.js";
import { execDml, queryOne } from "../baseRepository.js";

type EnsureIndex = { name: string; table: string; columns: string; unique?: boolean };

let initialized = false;

const TABLES: Array<{ name: string; ddl: string }> = [
  {
    name: "SESMT_COLABORADORES",
    ddl: `CREATE TABLE SESMT_COLABORADORES (
      ID VARCHAR2(36) PRIMARY KEY,
      MATRICULA VARCHAR2(40) NOT NULL,
      NOME VARCHAR2(180) NOT NULL,
      CPF VARCHAR2(20),
      UNIDADE VARCHAR2(40) NOT NULL,
      SETOR VARCHAR2(120),
      CARGO VARCHAR2(120),
      FUNCAO VARCHAR2(120),
      GESTOR VARCHAR2(120),
      DATA_ADMISSAO DATE,
      STATUS VARCHAR2(30) DEFAULT 'ATIVO' NOT NULL,
      GRUPO_RISCO VARCHAR2(240),
      SITUACAO_OCUPACIONAL VARCHAR2(200),
      SCORE_ATENCAO NUMBER(8,2) DEFAULT 0 NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_PROFISSIONAIS",
    ddl: `CREATE TABLE SESMT_PROFISSIONAIS (
      ID VARCHAR2(36) PRIMARY KEY,
      NOME VARCHAR2(180) NOT NULL,
      FORMACAO VARCHAR2(140),
      REGISTRO_PROFISSIONAL VARCHAR2(80),
      FUNCAO_LEGAL VARCHAR2(80),
      JORNADA_HORAS NUMBER(8,2),
      UNIDADE VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_DIMENSIONAMENTO",
    ddl: `CREATE TABLE SESMT_DIMENSIONAMENTO (
      ID VARCHAR2(36) PRIMARY KEY,
      UNIDADE VARCHAR2(40) NOT NULL,
      GRAU_RISCO NUMBER(5),
      EFETIVO NUMBER(10),
      EXIGIDO NUMBER(10),
      EXISTENTE NUMBER(10),
      MEMORIA_CALCULO VARCHAR2(2000),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_REQUISITOS_LEGAIS",
    ddl: `CREATE TABLE SESMT_REQUISITOS_LEGAIS (
      ID VARCHAR2(36) PRIMARY KEY,
      NORMA VARCHAR2(60) NOT NULL,
      ORIGEM_LEGAL VARCHAR2(240),
      APLICABILIDADE VARCHAR2(120),
      CRITERIO_AVALIACAO VARCHAR2(500),
      PERIODICIDADE VARCHAR2(60),
      RESPONSAVEL VARCHAR2(140),
      STATUS VARCHAR2(40),
      RISCO_DESCUMPRIMENTO VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_RISCOS",
    ddl: `CREATE TABLE SESMT_RISCOS (
      ID VARCHAR2(36) PRIMARY KEY,
      UNIDADE VARCHAR2(40),
      SETOR VARCHAR2(120),
      NR VARCHAR2(30),
      PERIGO VARCHAR2(500) NOT NULL,
      EVENTO_INDESEJADO VARCHAR2(500),
      CONSEQUENCIA VARCHAR2(500),
      CAUSA VARCHAR2(500),
      RISCO_INERENTE NUMBER(10,2),
      RISCO_RESIDUAL NUMBER(10,2),
      STATUS VARCHAR2(30),
      RESPONSAVEL VARCHAR2(140),
      REVISAO_AT DATE,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_BARREIRAS",
    ddl: `CREATE TABLE SESMT_BARREIRAS (
      ID VARCHAR2(36) PRIMARY KEY,
      RISCO_ID VARCHAR2(36) NOT NULL,
      TIPO_CONTROLE VARCHAR2(80),
      DESCRICAO VARCHAR2(500),
      EFICACIA NUMBER(8,2),
      STATUS VARCHAR2(30),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_PLANOS_ACAO",
    ddl: `CREATE TABLE SESMT_PLANOS_ACAO (
      ID VARCHAR2(36) PRIMARY KEY,
      RISCO_ID VARCHAR2(36),
      TITULO VARCHAR2(260),
      DESCRICAO VARCHAR2(1000),
      RESPONSAVEL VARCHAR2(140),
      PRAZO DATE,
      CRITICIDADE VARCHAR2(40),
      STATUS VARCHAR2(40),
      EVIDENCIA VARCHAR2(700),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_LAUDOS",
    ddl: `CREATE TABLE SESMT_LAUDOS (
      ID VARCHAR2(36) PRIMARY KEY,
      CODIGO VARCHAR2(60),
      TIPO VARCHAR2(80),
      TITULO VARCHAR2(260),
      UNIDADE VARCHAR2(40),
      DATA_EMISSAO DATE,
      DATA_VALIDADE DATE,
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_LAUDOS_VINCULOS",
    ddl: `CREATE TABLE SESMT_LAUDOS_VINCULOS (
      ID VARCHAR2(36) PRIMARY KEY,
      LAUDO_ID VARCHAR2(36) NOT NULL,
      TIPO_VINCULO VARCHAR2(80) NOT NULL,
      ENTIDADE_ID VARCHAR2(36),
      ENTIDADE_REF VARCHAR2(260),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_EPI_ENTREGAS",
    ddl: `CREATE TABLE SESMT_EPI_ENTREGAS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36) NOT NULL,
      DESCRICAO VARCHAR2(260) NOT NULL,
      CA VARCHAR2(60),
      DATA_ENTREGA DATE,
      DATA_DEVOLUCAO DATE,
      MOTIVO VARCHAR2(40),
      ASSINATURA NUMBER(1) DEFAULT 0 NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_EPC",
    ddl: `CREATE TABLE SESMT_EPC (
      ID VARCHAR2(36) PRIMARY KEY,
      CODIGO VARCHAR2(60),
      DESCRICAO VARCHAR2(260),
      UNIDADE VARCHAR2(40),
      LOCALIDADE VARCHAR2(200),
      CRITICIDADE VARCHAR2(40),
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_ACIDENTES",
    ddl: `CREATE TABLE SESMT_ACIDENTES (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      UNIDADE VARCHAR2(40),
      TIPO VARCHAR2(80),
      DATA_OCORRENCIA DATE,
      DESCRICAO VARCHAR2(1000),
      CAUSA VARCHAR2(600),
      NATUREZA_LESAO VARCHAR2(300),
      DIAS_AFASTAMENTO NUMBER(8) DEFAULT 0 NOT NULL,
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_CIPA",
    ddl: `CREATE TABLE SESMT_CIPA (
      ID VARCHAR2(36) PRIMARY KEY,
      UNIDADE VARCHAR2(40),
      MANDATO_INICIO DATE,
      MANDATO_FIM DATE,
      TITULARES NUMBER(8),
      SUPLENTES NUMBER(8),
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_TREINAMENTOS",
    ddl: `CREATE TABLE SESMT_TREINAMENTOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      NOME VARCHAR2(260),
      TIPO VARCHAR2(80),
      DATA_TREINAMENTO DATE,
      CARGA_HORARIA NUMBER(8,2),
      STATUS VARCHAR2(40),
      VALIDADE DATE,
      INSTRUTOR VARCHAR2(180),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_EXAMES",
    ddl: `CREATE TABLE SESMT_EXAMES (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36) NOT NULL,
      TIPO VARCHAR2(120) NOT NULL,
      DATA_EXAME DATE,
      RESULTADO VARCHAR2(200),
      STATUS VARCHAR2(40),
      LABORATORIO VARCHAR2(180),
      CUSTO NUMBER(12,2),
      VALIDADE DATE,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_ASOS",
    ddl: `CREATE TABLE SESMT_ASOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36) NOT NULL,
      TIPO VARCHAR2(80),
      DATA_ASO DATE,
      RESULTADO VARCHAR2(60),
      MEDICO VARCHAR2(180),
      VALIDADE DATE,
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_ATENDIMENTOS",
    ddl: `CREATE TABLE SESMT_ATENDIMENTOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36) NOT NULL,
      DATA_ATENDIMENTO DATE,
      TIPO VARCHAR2(120),
      DESCRICAO VARCHAR2(1000),
      PROFISSIONAL VARCHAR2(180),
      CID VARCHAR2(30),
      RESTRICAO VARCHAR2(300),
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_VACINAS",
    ddl: `CREATE TABLE SESMT_VACINAS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36) NOT NULL,
      VACINA VARCHAR2(160),
      DOSE VARCHAR2(80),
      DATA_APLICACAO DATE,
      STATUS VARCHAR2(40),
      CAMPANHA VARCHAR2(180),
      PROXIMA_DOSE DATE,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_MEDICACOES",
    ddl: `CREATE TABLE SESMT_MEDICACOES (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      MEDICAMENTO VARCHAR2(220),
      DATA_REGISTRO DATE,
      TIPO VARCHAR2(80),
      QUANTIDADE NUMBER(10,2),
      RESPONSAVEL VARCHAR2(180),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_AFASTAMENTOS",
    ddl: `CREATE TABLE SESMT_AFASTAMENTOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      TIPO VARCHAR2(120),
      DATA_INICIO DATE,
      DATA_FIM DATE,
      MOTIVO VARCHAR2(600),
      CID VARCHAR2(30),
      DIAS_AFASTADO NUMBER(8),
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_ATESTADOS",
    ddl: `CREATE TABLE SESMT_ATESTADOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      DATA_ATESTADO DATE,
      DIAS NUMBER(8),
      CID VARCHAR2(30),
      MEDICO VARCHAR2(180),
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_RESTRICOES",
    ddl: `CREATE TABLE SESMT_RESTRICOES (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      DESCRICAO VARCHAR2(600),
      DATA_INICIO DATE,
      DATA_FIM DATE,
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_COMUNICADOS",
    ddl: `CREATE TABLE SESMT_COMUNICADOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      TITULO VARCHAR2(260),
      TIPO VARCHAR2(80),
      DATA_REGISTRO DATE,
      STATUS VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_DOCUMENTOS",
    ddl: `CREATE TABLE SESMT_DOCUMENTOS (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36),
      NOME VARCHAR2(260),
      TIPO VARCHAR2(80),
      DATA_DOCUMENTO DATE,
      MIME_TYPE VARCHAR2(120),
      TAMANHO_BYTES NUMBER(18),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_ANEXOS",
    ddl: `CREATE TABLE SESMT_ANEXOS (
      ID VARCHAR2(36) PRIMARY KEY,
      ENTIDADE VARCHAR2(80) NOT NULL,
      ENTIDADE_ID VARCHAR2(36) NOT NULL,
      NOME_ARQUIVO VARCHAR2(260),
      STORAGE_KEY VARCHAR2(700),
      MIME_TYPE VARCHAR2(120),
      TAMANHO_BYTES NUMBER(18),
      USUARIO_UPLOAD VARCHAR2(180),
      DATA_UPLOAD TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_EVENTOS_COLABORADOR",
    ddl: `CREATE TABLE SESMT_EVENTOS_COLABORADOR (
      ID VARCHAR2(36) PRIMARY KEY,
      COLABORADOR_ID VARCHAR2(36) NOT NULL,
      DATA_EVENTO DATE NOT NULL,
      TIPO VARCHAR2(80) NOT NULL,
      TITULO VARCHAR2(260) NOT NULL,
      DESCRICAO VARCHAR2(1000),
      COR VARCHAR2(40),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
  {
    name: "SESMT_LOG_AUDITORIA",
    ddl: `CREATE TABLE SESMT_LOG_AUDITORIA (
      ID VARCHAR2(36) PRIMARY KEY,
      ACAO VARCHAR2(80) NOT NULL,
      ENTIDADE VARCHAR2(80) NOT NULL,
      ENTIDADE_ID VARCHAR2(36),
      USUARIO_ID VARCHAR2(120),
      USUARIO_NOME VARCHAR2(180),
      PERFIL VARCHAR2(80),
      DETALHE VARCHAR2(2000),
      PAYLOAD CLOB,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )`,
  },
];

const INDEXES: EnsureIndex[] = [
  { name: "UX_SESMT_COLAB_MAT", table: "SESMT_COLABORADORES", columns: "MATRICULA", unique: true },
  { name: "IDX_SESMT_COLAB_UNID", table: "SESMT_COLABORADORES", columns: "UNIDADE, STATUS" },
  { name: "IDX_SESMT_EXAME_COLAB", table: "SESMT_EXAMES", columns: "COLABORADOR_ID, DATA_EXAME" },
  { name: "IDX_SESMT_ASO_COLAB", table: "SESMT_ASOS", columns: "COLABORADOR_ID, DATA_ASO" },
  { name: "IDX_SESMT_TREIN_COLAB", table: "SESMT_TREINAMENTOS", columns: "COLABORADOR_ID, DATA_TREINAMENTO" },
  { name: "IDX_SESMT_EVENTO_COLAB", table: "SESMT_EVENTOS_COLABORADOR", columns: "COLABORADOR_ID, DATA_EVENTO" },
  { name: "IDX_SESMT_DOC_COLAB", table: "SESMT_DOCUMENTOS", columns: "COLABORADOR_ID, DATA_DOCUMENTO" },
  { name: "IDX_SESMT_AUD_DATA", table: "SESMT_LOG_AUDITORIA", columns: "CREATED_AT, ENTIDADE" },
];

async function tableExists(table: string): Promise<boolean> {
  try {
    await executeOracle(`SELECT * FROM ${table} WHERE 1 = 0`);
    return true;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("ORA-00942")) return false;
    throw error;
  }
}

async function indexExists(indexName: string): Promise<boolean> {
  const row = await queryOne<{ CNT: number }>(
    `SELECT COUNT(*) AS CNT FROM USER_INDEXES WHERE INDEX_NAME = :indexName`,
    { indexName: indexName.toUpperCase() },
  );
  return Number((row as any)?.CNT ?? 0) > 0;
}

async function createTableIfMissing(name: string, ddl: string): Promise<void> {
  if (await tableExists(name)) return;
  try {
    await execDml(ddl);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("ORA-00955") || message.includes("ORA-01031")) return;
    throw error;
  }
}

async function createIndexIfMissing(def: EnsureIndex): Promise<void> {
  if (!(await tableExists(def.table))) return;
  if (await indexExists(def.name)) return;
  const prefix = def.unique ? "CREATE UNIQUE INDEX" : "CREATE INDEX";
  try {
    await execDml(`${prefix} ${def.name} ON ${def.table} (${def.columns})`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes("ORA-00955") || message.includes("ORA-01408") || message.includes("ORA-01031")) return;
    throw error;
  }
}

async function ensureForeignKeys(): Promise<void> {
  const blocks = [
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_EXAMES ADD CONSTRAINT FK_SESMT_EXAME_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_ASOS ADD CONSTRAINT FK_SESMT_ASO_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_TREINAMENTOS ADD CONSTRAINT FK_SESMT_TREIN_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_ATENDIMENTOS ADD CONSTRAINT FK_SESMT_ATEND_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_VACINAS ADD CONSTRAINT FK_SESMT_VAC_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_MEDICACOES ADD CONSTRAINT FK_SESMT_MED_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_ACIDENTES ADD CONSTRAINT FK_SESMT_ACID_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_AFASTAMENTOS ADD CONSTRAINT FK_SESMT_AFST_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_ATESTADOS ADD CONSTRAINT FK_SESMT_ATEST_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_RESTRICOES ADD CONSTRAINT FK_SESMT_REST_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_COMUNICADOS ADD CONSTRAINT FK_SESMT_COM_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_DOCUMENTOS ADD CONSTRAINT FK_SESMT_DOC_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_EVENTOS_COLABORADOR ADD CONSTRAINT FK_SESMT_EVT_COLAB FOREIGN KEY (COLABORADOR_ID) REFERENCES SESMT_COLABORADORES(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_BARREIRAS ADD CONSTRAINT FK_SESMT_BARR_RISCO FOREIGN KEY (RISCO_ID) REFERENCES SESMT_RISCOS(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_PLANOS_ACAO ADD CONSTRAINT FK_SESMT_PLANO_RISCO FOREIGN KEY (RISCO_ID) REFERENCES SESMT_RISCOS(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
    `BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SESMT_LAUDOS_VINCULOS ADD CONSTRAINT FK_SESMT_VINC_LAUDO FOREIGN KEY (LAUDO_ID) REFERENCES SESMT_LAUDOS(ID)'; EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2261,-2275,-2270,-2291,-2443) THEN RAISE; END IF; END;`,
  ];
  for (const sql of blocks) {
    try {
      await execDml(sql);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (message.includes("ORA-01031")) continue;
      throw error;
    }
  }
}

async function countRows(table: string): Promise<number> {
  const row = await queryOne<{ CNT: number }>(`SELECT COUNT(*) AS CNT FROM ${table}`);
  return Number((row as any)?.CNT ?? 0);
}

async function seedSesmtCoreIfNeeded(): Promise<void> {
  if ((await countRows("SESMT_COLABORADORES")) > 0) return;

  await execDml(
    `INSERT INTO SESMT_COLABORADORES (
      ID, MATRICULA, NOME, CPF, UNIDADE, SETOR, CARGO, FUNCAO, GESTOR, DATA_ADMISSAO, STATUS, GRUPO_RISCO, SITUACAO_OCUPACIONAL, SCORE_ATENCAO
    ) VALUES (
      'COL-001', 'MAT-4521', 'Carlos Eduardo Silva', '123.456.789-00', 'MAO', 'Producao', 'Operador de Maquinas', 'Operador III', 'Ana Souza', DATE '2019-03-15', 'ATIVO', 'GHE-02 - Ruido e Poeira', 'Regular com pendencias', 72
    )`,
  );
  await execDml(
    `INSERT INTO SESMT_COLABORADORES (
      ID, MATRICULA, NOME, CPF, UNIDADE, SETOR, CARGO, FUNCAO, GESTOR, DATA_ADMISSAO, STATUS, GRUPO_RISCO, SITUACAO_OCUPACIONAL, SCORE_ATENCAO
    ) VALUES (
      'COL-002', 'MAT-3287', 'Maria Fernanda Costa', '987.654.321-00', 'BEL', 'Logistica', 'Auxiliar de Logistica', 'Auxiliar I', 'Bruno Lima', DATE '2021-08-01', 'ATIVO', 'GHE-01 - Ergonomico', 'Regular', 91
    )`,
  );
  await execDml(
    `INSERT INTO SESMT_COLABORADORES (
      ID, MATRICULA, NOME, CPF, UNIDADE, SETOR, CARGO, FUNCAO, GESTOR, DATA_ADMISSAO, STATUS, GRUPO_RISCO, SITUACAO_OCUPACIONAL, SCORE_ATENCAO
    ) VALUES (
      'COL-003', 'MAT-1190', 'Jose Roberto Mendes', '456.789.123-00', 'AGR', 'Manutencao', 'Eletricista Industrial', 'Eletricista II', 'Carla Reis', DATE '2017-01-10', 'AFASTADO', 'GHE-05 - Eletricidade', 'Afastado - acidente de trabalho', 38
    )`,
  );

  await execDml(`INSERT INTO SESMT_EXAMES (ID, COLABORADOR_ID, TIPO, DATA_EXAME, RESULTADO, STATUS, LABORATORIO, CUSTO, VALIDADE) VALUES ('EX-001','COL-001','Audiometria',DATE '2025-11-20','Normal','REALIZADO','AudioLab',85,DATE '2026-11-20')`);
  await execDml(`INSERT INTO SESMT_EXAMES (ID, COLABORADOR_ID, TIPO, DATA_EXAME, RESULTADO, STATUS, LABORATORIO, CUSTO, VALIDADE) VALUES ('EX-002','COL-001','Espirometria',DATE '2025-10-05','Normal','REALIZADO','PulmoCenter',120,DATE '2026-10-05')`);
  await execDml(`INSERT INTO SESMT_EXAMES (ID, COLABORADOR_ID, TIPO, DATA_EXAME, RESULTADO, STATUS, LABORATORIO, CUSTO, VALIDADE) VALUES ('EX-003','COL-001','Raio-X Torax',DATE '2024-06-10','Normal','VENCIDO','RadioDiag',150,DATE '2025-06-10')`);

  await execDml(`INSERT INTO SESMT_ASOS (ID, COLABORADOR_ID, TIPO, DATA_ASO, RESULTADO, MEDICO, VALIDADE, STATUS) VALUES ('ASO-001','COL-001','PERIODICO',DATE '2025-11-20','APTO','Dr. Ricardo Alves',DATE '2026-11-20','VIGENTE')`);
  await execDml(`INSERT INTO SESMT_ASOS (ID, COLABORADOR_ID, TIPO, DATA_ASO, RESULTADO, MEDICO, VALIDADE, STATUS) VALUES ('ASO-002','COL-001','PERIODICO',DATE '2024-11-18','APTO','Dr. Ricardo Alves',DATE '2025-11-18','VENCIDO')`);

  await execDml(`INSERT INTO SESMT_TREINAMENTOS (ID, COLABORADOR_ID, NOME, TIPO, DATA_TREINAMENTO, CARGA_HORARIA, STATUS, VALIDADE, INSTRUTOR) VALUES ('TR-001','COL-001','Integracao SESMT','INTEGRACAO',DATE '2019-03-16',8,'CONCLUIDO',NULL,'Equipe SESMT')`);
  await execDml(`INSERT INTO SESMT_TREINAMENTOS (ID, COLABORADOR_ID, NOME, TIPO, DATA_TREINAMENTO, CARGA_HORARIA, STATUS, VALIDADE, INSTRUTOR) VALUES ('TR-002','COL-001','NR-12 - Seguranca em Maquinas','NR',DATE '2024-02-10',16,'VENCIDO',DATE '2026-02-10','Eng. Paulo Barros')`);

  await execDml(`INSERT INTO SESMT_ATENDIMENTOS (ID, COLABORADOR_ID, DATA_ATENDIMENTO, TIPO, DESCRICAO, PROFISSIONAL, CID, RESTRICAO, STATUS) VALUES ('ATD-001','COL-001',DATE '2026-02-18','Consulta ambulatorial','Dor lombar aguda apos esforco','Enf. Claudia Menezes',NULL,'Evitar carga acima de 15kg por 7 dias','CONCLUIDO')`);
  await execDml(`INSERT INTO SESMT_VACINAS (ID, COLABORADOR_ID, VACINA, DOSE, DATA_APLICACAO, STATUS, CAMPANHA, PROXIMA_DOSE) VALUES ('VAC-001','COL-001','Tetano (dT)','Reforco',DATE '2024-08-10','APLICADA',NULL,DATE '2034-08-10')`);
  await execDml(`INSERT INTO SESMT_VACINAS (ID, COLABORADOR_ID, VACINA, DOSE, DATA_APLICACAO, STATUS, CAMPANHA, PROXIMA_DOSE) VALUES ('VAC-002','COL-001','Hepatite B','3a dose',NULL,'PENDENTE',NULL,NULL)`);
  await execDml(`INSERT INTO SESMT_MEDICACOES (ID, COLABORADOR_ID, MEDICAMENTO, DATA_REGISTRO, TIPO, QUANTIDADE, RESPONSAVEL) VALUES ('MED-001','COL-001','Dipirona 500mg',DATE '2026-02-18','DISPENSACAO',4,'Enf. Claudia Menezes')`);
  await execDml(`INSERT INTO SESMT_ACIDENTES (ID, COLABORADOR_ID, UNIDADE, TIPO, DATA_OCORRENCIA, DESCRICAO, CAUSA, NATUREZA_LESAO, DIAS_AFASTAMENTO, STATUS) VALUES ('ACD-001','COL-001','MAO','INCIDENTE',DATE '2025-06-22','Corte superficial na mao durante operacao','Falha no procedimento','Corte',0,'ENCERRADO')`);
  await execDml(`INSERT INTO SESMT_AFASTAMENTOS (ID, COLABORADOR_ID, TIPO, DATA_INICIO, DATA_FIM, MOTIVO, CID, DIAS_AFASTADO, STATUS) VALUES ('AF-001','COL-001','Licenca Medica',DATE '2025-01-10',DATE '2025-01-14','Virose - atestado medico','J11',4,'ENCERRADO')`);
  await execDml(`INSERT INTO SESMT_ATESTADOS (ID, COLABORADOR_ID, DATA_ATESTADO, DIAS, CID, MEDICO, STATUS) VALUES ('ATE-001','COL-001',DATE '2025-01-10',4,'J11','Dr. Fabio Maia','ACEITO')`);
  await execDml(`INSERT INTO SESMT_RESTRICOES (ID, COLABORADOR_ID, DESCRICAO, DATA_INICIO, DATA_FIM, STATUS) VALUES ('RES-001','COL-001','Evitar carga acima de 15kg por 7 dias',DATE '2026-02-18',DATE '2026-02-25','ENCERRADO')`);
  await execDml(`INSERT INTO SESMT_EPI_ENTREGAS (ID, COLABORADOR_ID, DESCRICAO, CA, DATA_ENTREGA, MOTIVO, ASSINATURA) VALUES ('EPI-001','COL-001','Protetor Auricular tipo concha','CA-14235',DATE '2025-12-01','ENTREGA',1)`);
  await execDml(`INSERT INTO SESMT_COMUNICADOS (ID, COLABORADOR_ID, TITULO, TIPO, DATA_REGISTRO, STATUS) VALUES ('COM-001','COL-001','Campanha de uso correto de EPI','CAMPANHA',DATE '2026-02-10','LIDO')`);
  await execDml(`INSERT INTO SESMT_DOCUMENTOS (ID, COLABORADOR_ID, NOME, TIPO, DATA_DOCUMENTO, MIME_TYPE, TAMANHO_BYTES) VALUES ('DOC-001','COL-001','ASO Periodico 2025','ASO',DATE '2025-11-20','application/pdf',235001)`);

  const events = [
    { tipo: "ATENDIMENTO", titulo: "Atendimento ambulatorial", descricao: "Dor lombar - restricao temporaria", dataEvento: "2026-02-18", cor: "info" },
    { tipo: "EPI", titulo: "Entrega de EPI", descricao: "Protetor auricular tipo concha - CA-14235", dataEvento: "2025-12-01", cor: "success" },
    { tipo: "EXAME", titulo: "Audiometria realizada", descricao: "Resultado normal - Lab AudioLab", dataEvento: "2025-11-20", cor: "success" },
    { tipo: "ASO", titulo: "ASO Periodico emitido", descricao: "Apto - Dr. Ricardo Alves", dataEvento: "2025-11-20", cor: "success" },
    { tipo: "ACIDENTE", titulo: "Incidente - corte superficial", descricao: "Corte na mao durante operacao", dataEvento: "2025-06-22", cor: "destructive" },
    { tipo: "ADMISSAO", titulo: "Admissao", descricao: "Operador de Maquinas - Unidade MAO", dataEvento: "2019-03-15", cor: "info" },
  ];
  for (const event of events) {
    await execDml(
      `INSERT INTO SESMT_EVENTOS_COLABORADOR (ID, COLABORADOR_ID, DATA_EVENTO, TIPO, TITULO, DESCRICAO, COR)
       VALUES (:id, 'COL-001', TO_DATE(:dataEvento, 'YYYY-MM-DD'), :tipo, :titulo, :descricao, :cor)`,
      { id: randomUUID(), ...event },
    );
  }
}

export async function ensureSesmtTables(): Promise<void> {
  if (!isOracleEnabled() || initialized) return;
  for (const table of TABLES) await createTableIfMissing(table.name, table.ddl);
  await ensureForeignKeys();
  for (const index of INDEXES) await createIndexIfMissing(index);
  await seedSesmtCoreIfNeeded();
  initialized = true;
}

