/**
 * Ensures all INS_* tables exist in Oracle.
 * Uses CREATE TABLE wrapped in PL/SQL exception block (idempotent).
 */
import { execDml } from "../baseRepository.js";
import { isOracleEnabled } from "../../db/oracle.js";

let initialized = false;

const DDL_STATEMENTS = [
  `CREATE TABLE INS_SETOR (
    ID VARCHAR2(40) PRIMARY KEY, NOME VARCHAR2(120) NOT NULL,
    ORDEM NUMBER(4) NOT NULL, ATIVO NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_USUARIO_SETOR (
    ID VARCHAR2(40) PRIMARY KEY, USER_ID VARCHAR2(80) NOT NULL,
    SETOR_ID VARCHAR2(40) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_MODELO_CHECKLIST (
    ID VARCHAR2(40) PRIMARY KEY, NOME VARCHAR2(200) NOT NULL,
    SETOR_ID VARCHAR2(40) NOT NULL, DESCRICAO VARCHAR2(500),
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL, ORDEM NUMBER(4) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_MODELO_CHECKLIST_ITEM (
    ID VARCHAR2(40) PRIMARY KEY, MODELO_ID VARCHAR2(40) NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL, ORDEM NUMBER(4) NOT NULL,
    OBRIGATORIO NUMBER(1) DEFAULT 1 NOT NULL,
    EXIGE_EVIDENCIA NUMBER(1) DEFAULT 1 NOT NULL,
    EXIGE_TIPO_NC NUMBER(1) DEFAULT 1 NOT NULL,
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL)`,
  `CREATE TABLE INS_TIPO_NC (
    ID VARCHAR2(40) PRIMARY KEY, SETOR_ID VARCHAR2(40),
    NOME VARCHAR2(300) NOT NULL, CATEGORIA VARCHAR2(60) DEFAULT 'Processo',
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL)`,
  `CREATE TABLE INS_EXECUCAO (
    ID VARCHAR2(40) PRIMARY KEY, MODELO_ID VARCHAR2(40) NOT NULL,
    SETOR_ID VARCHAR2(40) NOT NULL, INSPETOR VARCHAR2(120),
    STATUS VARCHAR2(30) DEFAULT 'EM_ANDAMENTO',
    DATA_INICIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    DATA_FIM TIMESTAMP, OBSERVACOES VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_EXECUCAO_ITEM (
    ID VARCHAR2(40) PRIMARY KEY, EXECUCAO_ID VARCHAR2(40) NOT NULL,
    ITEM_ID VARCHAR2(40) NOT NULL, STATUS VARCHAR2(30) NOT NULL,
    TIPO_NC_ID VARCHAR2(40), OBSERVACAO VARCHAR2(1000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_EXECUCAO_ITEM_EVIDENCIA (
    ID VARCHAR2(40) PRIMARY KEY, EXEC_ITEM_ID VARCHAR2(40) NOT NULL,
    ARQUIVO_URL VARCHAR2(500) NOT NULL, ARQUIVO_NOME VARCHAR2(200),
    TIPO_MIME VARCHAR2(80), CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_MOLA_MAQUINA (
    ID VARCHAR2(40) PRIMARY KEY, CODIGO VARCHAR2(20) NOT NULL,
    DESCRICAO VARCHAR2(200), ATIVO NUMBER(1) DEFAULT 1 NOT NULL)`,
  `CREATE TABLE INS_MOLA_PADRAO (
    ID VARCHAR2(40) PRIMARY KEY, ALTURA_TIPO VARCHAR2(20) NOT NULL,
    ITEM VARCHAR2(20), DESCRICAO VARCHAR2(300) NOT NULL,
    PADRAO VARCHAR2(100), MINIMO NUMBER(10,2) DEFAULT 0,
    MAXIMO NUMBER(10,2) DEFAULT 0, UNIDADE VARCHAR2(40),
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL)`,
  `CREATE TABLE INS_MOLA_INSPECAO (
    ID VARCHAR2(40) PRIMARY KEY, MAQUINA_ID VARCHAR2(40) NOT NULL,
    INSPETOR VARCHAR2(120), STATUS VARCHAR2(30) DEFAULT 'EM_ANDAMENTO',
    MAQUINA_PARADA NUMBER(1) DEFAULT 0,
    DATA_INSPECAO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    OBSERVACOES VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
  `CREATE TABLE INS_MOLA_INSPECAO_AMOSTRA (
    ID VARCHAR2(40) PRIMARY KEY, INSPECAO_ID VARCHAR2(40) NOT NULL,
    PADRAO_ID VARCHAR2(40) NOT NULL, VALOR_MEDIDO NUMBER(10,2),
    CONFORME NUMBER(1), OBSERVACAO VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)`,
];

export async function ensureInspecoesTables(): Promise<void> {
  if (!isOracleEnabled() || initialized) return;
  for (const ddl of DDL_STATEMENTS) {
    await execDml(`BEGIN EXECUTE IMMEDIATE '${ddl.replace(/'/g, "''")}'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`);
  }
  initialized = true;
}
